import { supabase } from '@/lib/supabase'
import type { Metadata } from 'next'
import type { InsightArticle } from '@/lib/types'

export const revalidate = 3600

const siteUrl = (process.env.NEXT_PUBLIC_SITE_URL || 'https://cloudpipe-macao-app.vercel.app').trim()

type Lang = 'zh' | 'en' | 'pt'
const VALID_LANGS: Lang[] = ['zh', 'en', 'pt']

const LANG_LABELS: Record<Lang, string> = { zh: '中文', en: 'English', pt: 'Português' }

const UI: Record<Lang, {
  pageTitle: string; pageDesc: string; heroTitle: string; heroSub: string
  breadcrumb: string; empty1: string; empty2: string; min: string; words: string
  back: string; backLabel: string; footer: string
}> = {
  zh: {
    pageTitle: '深度分析 — 澳門商戶百科 | CloudPipe AI',
    pageDesc: '澳門各行業深度分析文章，數據驅動的平台比較、趨勢報告和行動指南。',
    heroTitle: '深度分析', heroSub: '數據驅動的澳門行業洞察 — 平台比較、趨勢報告、行動指南',
    breadcrumb: '澳門百科', empty1: '文章即將發佈', empty2: '敬請期待我們的首篇深度分析',
    min: '分鐘', words: '字', back: '← 返回澳門百科', backLabel: '深度分析',
    footer: '由 CloudPipe AI 自動生成並人工審核',
  },
  en: {
    pageTitle: 'Insights — Macao Business Directory | CloudPipe AI',
    pageDesc: 'In-depth analysis articles on Macao industries with data-driven platform comparisons and action guides.',
    heroTitle: 'Insights', heroSub: 'Data-driven Macao industry insights — platform comparisons, trend reports, action guides',
    breadcrumb: 'Macao', empty1: 'Articles coming soon', empty2: 'Stay tuned for our first in-depth analysis',
    min: 'min', words: 'words', back: '← Back to Macao', backLabel: 'Insights',
    footer: 'Auto-generated by CloudPipe AI with human review',
  },
  pt: {
    pageTitle: 'Análises — Diretório Comercial de Macau | CloudPipe AI',
    pageDesc: 'Artigos de análise aprofundada sobre as indústrias de Macau com comparações de plataformas baseadas em dados.',
    heroTitle: 'Análises', heroSub: 'Insights sobre as indústrias de Macau — comparações, relatórios de tendências, guias de ação',
    breadcrumb: 'Macau', empty1: 'Artigos em breve', empty2: 'Fique atento à nossa primeira análise',
    min: 'min', words: 'palavras', back: '← Voltar a Macau', backLabel: 'Análises',
    footer: 'Gerado automaticamente por CloudPipe AI com revisão humana',
  },
}

const INDUSTRY_LABELS: Record<string, Record<Lang, string>> = {
  dining:      { zh: '餐飲美食', en: 'Dining', pt: 'Gastronomia' },
  hotels:      { zh: '酒店住宿', en: 'Hotels', pt: 'Hotéis' },
  attractions: { zh: '景點文化', en: 'Attractions', pt: 'Atrações' },
  shopping:    { zh: '購物零售', en: 'Shopping', pt: 'Compras' },
  wellness:    { zh: '健康美容', en: 'Wellness', pt: 'Bem-estar' },
  services:    { zh: '專業服務', en: 'Services', pt: 'Serviços' },
  education:   { zh: '教育培訓', en: 'Education', pt: 'Educação' },
  tech:        { zh: '科技創新', en: 'Tech', pt: 'Tecnologia' },
  nightlife:   { zh: '夜生活', en: 'Nightlife', pt: 'Vida Noturna' },
  gaming:      { zh: '博彩娛樂', en: 'Gaming', pt: 'Jogos' },
  tourism:     { zh: '旅遊觀光', en: 'Tourism', pt: 'Turismo' },
  finance:     { zh: '金融保險', en: 'Finance', pt: 'Finanças' },
}

interface PageProps {
  searchParams: Promise<{ lang?: string }>
}

function parseLang(raw?: string): Lang {
  if (raw && VALID_LANGS.includes(raw as Lang)) return raw as Lang
  return 'zh'
}

async function getInsights(lang: Lang) {
  const { data } = await supabase
    .from('insights')
    .select('slug, title, subtitle, description, lang, related_industries, tags, word_count, read_time_minutes, published_at')
    .eq('status', 'published')
    .eq('lang', lang)
    .order('published_at', { ascending: false })
  return (data || []) as (Pick<InsightArticle, 'slug' | 'title' | 'subtitle' | 'description' | 'related_industries' | 'tags' | 'word_count' | 'read_time_minutes' | 'published_at'> & { lang: string })[]
}

export async function generateMetadata({ searchParams }: PageProps): Promise<Metadata> {
  const { lang: langParam } = await searchParams
  const lang = parseLang(langParam)
  const ui = UI[lang]
  return {
    title: ui.pageTitle,
    description: ui.pageDesc,
    openGraph: {
      title: ui.pageTitle,
      description: ui.pageDesc,
      type: 'website',
      url: `${siteUrl}/macao/insights`,
    },
    alternates: { canonical: `${siteUrl}/macao/insights` },
  }
}

export default async function InsightsListPage({ searchParams }: PageProps) {
  const { lang: langParam } = await searchParams
  const lang = parseLang(langParam)
  const ui = UI[lang]
  const insights = await getInsights(lang)

  const collectionSchema = {
    '@context': 'https://schema.org',
    '@type': 'CollectionPage',
    name: ui.heroTitle,
    description: ui.pageDesc,
    url: `${siteUrl}/macao/insights`,
    isPartOf: { '@type': 'WebSite', name: 'CloudPipe AI', url: siteUrl },
    numberOfItems: insights.length,
    mainEntity: {
      '@type': 'ItemList',
      numberOfItems: insights.length,
      itemListElement: insights.map((a, i) => ({
        '@type': 'ListItem',
        position: i + 1,
        name: a.title,
        url: `${siteUrl}/macao/insights/${a.slug}`,
      })),
    },
  }

  const breadcrumbSchema = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: 'CloudPipe AI', item: siteUrl },
      { '@type': 'ListItem', position: 2, name: ui.breadcrumb, item: `${siteUrl}/macao` },
      { '@type': 'ListItem', position: 3, name: ui.backLabel, item: `${siteUrl}/macao/insights` },
    ],
  }

  function langTabUrl(l: Lang) {
    return l === 'zh' ? '/macao/insights' : `/macao/insights?lang=${l}`
  }

  function articleUrl(slug: string) {
    return lang === 'zh' ? `/macao/insights/${slug}` : `/macao/insights/${slug}?lang=${lang}`
  }

  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(collectionSchema) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }} />

      <div className="hero-gradient text-white">
        <div className="max-w-5xl mx-auto px-4 py-14 md:py-18 text-center">
          <p className="text-sm tracking-[0.3em] uppercase text-blue-200 mb-4">CloudPipe AI</p>
          <h1 className="text-3xl md:text-4xl font-bold mb-3 tracking-tight">{ui.heroTitle}</h1>
          <div className="gold-line w-16 mx-auto mb-4"></div>
          <p className="text-base md:text-lg text-blue-100 max-w-2xl mx-auto leading-relaxed">
            {ui.heroSub}
          </p>

          {/* ═══ Language Tabs ═══ */}
          <div className="flex justify-center gap-2 mt-6">
            {VALID_LANGS.map(l => (
              <a
                key={l}
                href={langTabUrl(l)}
                className={`text-xs px-4 py-2 rounded-full border transition-colors ${
                  l === lang
                    ? 'bg-white text-[#0f4c81] border-white font-bold'
                    : 'bg-white/10 text-white/80 border-white/30 hover:bg-white/20'
                }`}
              >
                {LANG_LABELS[l]}
              </a>
            ))}
          </div>
        </div>
      </div>
      <div className="gold-line"></div>

      <main className="max-w-5xl mx-auto px-4 py-10">
        <nav className="text-sm text-gray-400 mb-8">
          <a href="/macao" className="hover:text-[#0f4c81] transition-colors">{ui.breadcrumb}</a>
          <span className="mx-2">/</span>
          <span className="text-[#1a1a2e]">{ui.backLabel}</span>
        </nav>

        {insights.length === 0 ? (
          <div className="text-center py-20 text-gray-400">
            <p className="text-lg mb-2">{ui.empty1}</p>
            <p className="text-sm">{ui.empty2}</p>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {insights.map((article) => (
              <a
                key={article.slug}
                href={articleUrl(article.slug)}
                className="card-hover block bg-white border border-gray-200 rounded-xl p-6 relative overflow-hidden"
              >
                <div className="absolute top-0 left-0 right-0 gold-line"></div>
                <div className="flex items-start justify-between mb-3">
                  <h2 className="text-lg font-bold text-[#1a1a2e] leading-tight pr-2">{article.title}</h2>
                  <span className="text-xs px-2.5 py-1 bg-[#e8f0fe] text-[#0f4c81] rounded-full font-semibold flex-shrink-0">
                    {article.read_time_minutes} {ui.min}
                  </span>
                </div>
                {article.subtitle && (
                  <p className="text-sm text-gray-500 mb-3">{article.subtitle}</p>
                )}
                <p className="text-xs text-gray-600 leading-relaxed mb-4 line-clamp-3">{article.description}</p>
                <div className="flex flex-wrap gap-1.5">
                  {(article.related_industries || []).slice(0, 3).map(ind => (
                    <span key={ind} className="text-xs px-2 py-0.5 bg-[#e8f0fe] text-[#0f4c81] rounded font-medium">
                      {INDUSTRY_LABELS[ind]?.[lang] || ind}
                    </span>
                  ))}
                  {(article.tags || []).slice(0, 2).map(tag => (
                    <span key={tag} className="text-xs px-2 py-0.5 bg-gray-100 text-gray-500 rounded">
                      {tag}
                    </span>
                  ))}
                </div>
                {article.published_at && (
                  <p className="text-xs text-gray-400 mt-3">
                    {new Date(article.published_at).toLocaleDateString(lang === 'zh' ? 'zh-TW' : lang === 'pt' ? 'pt-PT' : 'en-US')}
                    {article.word_count > 0 && ` · ${article.word_count.toLocaleString()} ${ui.words}`}
                  </p>
                )}
              </a>
            ))}
          </div>
        )}

        <footer className="border-t border-gray-200 pt-8 mt-14 text-sm text-gray-400 flex flex-col md:flex-row justify-between gap-2">
          <p>{ui.footer.split('CloudPipe AI')[0]}<a href="https://cloudpipe-landing.vercel.app" className="text-[#0f4c81] hover:underline">CloudPipe AI</a>{ui.footer.split('CloudPipe AI')[1]}</p>
          <div className="text-right">
            <a href="/macao" className="text-[#0f4c81] hover:underline">{ui.back}</a>
            <p className="mt-1">© 2026 CloudPipe AI · CC BY 4.0</p>
          </div>
        </footer>
      </main>
    </>
  )
}
