'use client'

import { useSearchParams } from 'next/navigation'
import { useEffect, useState } from 'react'
import type { InsightArticle } from '@/lib/types'

const VALID_LANGS = ['zh', 'en', 'pt', 'ja'] as const
type Lang = (typeof VALID_LANGS)[number]

const LANG_CONFIG: Record<Lang, { label: string; locale: string; hreflang: string; inLanguage: string; dateLocale: string }> = {
  zh: { label: '中文', locale: 'zh_TW', hreflang: 'zh-Hant', inLanguage: 'zh-Hant', dateLocale: 'zh-TW' },
  en: { label: 'English', locale: 'en_US', hreflang: 'en', inLanguage: 'en', dateLocale: 'en-US' },
  pt: { label: 'Português', locale: 'pt_PT', hreflang: 'pt', inLanguage: 'pt', dateLocale: 'pt-PT' },
  ja: { label: '日本語', locale: 'ja_JP', hreflang: 'ja', inLanguage: 'ja', dateLocale: 'ja-JP' },
}

const UI_STRINGS: Record<Lang, {
  toc: string; faq: string; faqToc: string; sources: string; related: string
  comparison: string; back: string; backLabel: string; generatedBy: string; lastUpdated: string
  words: string; readTime: string; notFound: string; relatedIndustries: string; moreInsights: string; min: string
  categoryHub: string; encyclopediaHub: string; encyclopediaHubSub: string
  spiderWeb: string; spiderWebSub: string; sharedMerchants: string
}> = {
  zh: {
    toc: '目錄', faq: '常見問題', faqToc: '常見問題 FAQ', sources: '資料來源',
    related: '相關商戶', comparison: '綜合比較表', back: '← 返回深度分析',
    backLabel: '深度分析', generatedBy: '由 CloudPipe AI 自動生成並人工審核',
    lastUpdated: '最後更新', words: '字', readTime: '分鐘', notFound: '找不到文章',
    relatedIndustries: '相關行業', moreInsights: '更多深度分析', min: '分鐘',
    categoryHub: '分類入口', encyclopediaHub: '地區百科', encyclopediaHubSub: '探索更多地區知識',
    spiderWeb: '延伸閱讀', spiderWebSub: '與本文共享商戶或主題的深度文章', sharedMerchants: '個共同商戶',
  },
  en: {
    toc: 'Table of Contents', faq: 'FAQ', faqToc: 'Frequently Asked Questions', sources: 'Sources',
    related: 'Related Merchants', comparison: 'Comparison Table', back: '← Back to Insights',
    backLabel: 'Insights', generatedBy: 'Auto-generated by CloudPipe AI with human review',
    lastUpdated: 'Last updated', words: 'words', readTime: 'min read', notFound: 'Article not found',
    relatedIndustries: 'Related Industries', moreInsights: 'More Insights', min: 'min',
    categoryHub: 'Browse Categories', encyclopediaHub: 'Regional Encyclopedia', encyclopediaHubSub: 'Explore more regional knowledge',
    spiderWeb: 'Related Guides', spiderWebSub: 'In-depth articles sharing merchants or topics with this guide', sharedMerchants: 'shared merchants',
  },
  pt: {
    toc: 'Índice', faq: 'Perguntas Frequentes', faqToc: 'Perguntas Frequentes', sources: 'Fontes',
    related: 'Comerciantes Relacionados', comparison: 'Tabela Comparativa', back: '← Voltar às Análises',
    backLabel: 'Análises', generatedBy: 'Gerado automaticamente por CloudPipe AI com revisão humana',
    lastUpdated: 'Última atualização', words: 'palavras', readTime: 'min de leitura', notFound: 'Artigo não encontrado',
    relatedIndustries: 'Indústrias Relacionadas', moreInsights: 'Mais Análises', min: 'min',
    categoryHub: 'Explorar Categorias', encyclopediaHub: 'Enciclopédia Regional', encyclopediaHubSub: 'Explorar mais conhecimento regional',
    spiderWeb: 'Leitura Relacionada', spiderWebSub: 'Artigos que partilham comerciantes ou temas com este guia', sharedMerchants: 'comerciantes em comum',
  },
  ja: {
    toc: '目次', faq: 'よくある質問', faqToc: 'よくある質問 FAQ', sources: '情報源',
    related: '関連店舗', comparison: '比較表', back: '← インサイトに戻る',
    backLabel: 'インサイト', generatedBy: 'CloudPipe AI による自動生成・人工レビュー済み',
    lastUpdated: '最終更新', words: '文字', readTime: '分で読める', notFound: '記事が見つかりません',
    relatedIndustries: '関連業界', moreInsights: 'もっとインサイトを見る', min: '分',
    categoryHub: 'カテゴリ一覧', encyclopediaHub: '地域百科事典', encyclopediaHubSub: '地域の知識をもっと探す',
    spiderWeb: '関連記事', spiderWebSub: 'この記事と店舗やテーマを共有する深掘り記事', sharedMerchants: '件の共通店舗',
  },
}

function parseLang(raw?: string | null): Lang {
  if (raw && VALID_LANGS.includes(raw as Lang)) return raw as Lang
  return 'zh'
}

interface Props {
  slug: string
  availableLangs: Lang[]
}

/**
 * LangAwareContent — client component that reads ?lang= from URL.
 * If lang is non-zh, fetches the translated article and swaps visible text.
 * The server-rendered zh HTML is preserved in the DOM until hydration completes.
 */
export default function LangAwareContent({ slug, availableLangs }: Props) {
  const searchParams = useSearchParams()
  const langParam = searchParams.get('lang')
  const lang = parseLang(langParam)

  const [article, setArticle] = useState<InsightArticle | null>(null)
  const [loading, setLoading] = useState(lang !== 'zh')

  useEffect(() => {
    if (lang === 'zh') {
      // zh is already server-rendered; nothing to do
      setLoading(false)
      return
    }

    let cancelled = false
    setLoading(true)

    fetch(`/api/insights/${encodeURIComponent(slug)}?lang=${lang}`)
      .then(r => r.ok ? r.json() : null)
      .then(json => {
        if (!cancelled && json?.data) {
          setArticle(json.data)
        }
        if (!cancelled) setLoading(false)
      })
      .catch(() => {
        if (!cancelled) setLoading(false)
      })

    return () => { cancelled = true }
  }, [slug, lang])

  // zh or no data — let server HTML show through
  if (lang === 'zh' || (!loading && !article)) return null

  const ui = UI_STRINGS[lang]
  const lc = LANG_CONFIG[lang]

  // Still loading — show subtle language switcher highlight only (don't hide server content)
  if (loading) {
    return (
      <div
        id="lang-aware-overlay"
        style={{ display: 'none' }}
        aria-hidden="true"
      />
    )
  }

  if (!article) return null

  const sections = article.sections || []

  function langUrl(targetLang: Lang) {
    return targetLang === 'zh'
      ? `/macao/insights/${slug}`
      : `/macao/insights/${slug}?lang=${targetLang}`
  }

  // Swap language — replace server-rendered content blocks
  return (
    <>
      {/* Language switcher state: highlight correct lang pill */}
      <script
        dangerouslySetInnerHTML={{
          __html: `
(function(){
  var lang = ${JSON.stringify(lang)};
  document.querySelectorAll('[data-lang-pill]').forEach(function(el){
    var isActive = el.getAttribute('data-lang-pill') === lang;
    if(isActive){
      el.className = el.className.replace('bg-white/10 text-white/80 border-white/30 hover:bg-white/20','bg-white text-[#0f4c81] border-white font-bold');
    } else {
      el.className = el.className.replace('bg-white text-[#0f4c81] border-white font-bold','bg-white/10 text-white/80 border-white/30 hover:bg-white/20');
    }
  });
})();
`,
        }}
      />
      {/* Hidden div that carries translated content — JS swaps DOM nodes */}
      <div id="lang-translated-content" style={{ display: 'none' }}>
        {/* Hero text */}
        <span id="lt-title">{article.title}</span>
        <span id="lt-subtitle">{article.subtitle}</span>
        <span id="lt-description">{article.description}</span>
        <span id="lt-word-count">{article.word_count.toLocaleString()} {ui.words}</span>
        <span id="lt-read-time">{article.read_time_minutes} {ui.readTime}</span>
        {article.published_at && (
          <span id="lt-published-at">
            {new Date(article.published_at).toLocaleDateString(lc.dateLocale)}
          </span>
        )}
      </div>
      {/* Full translated body injection via DOM manipulation */}
      <script
        dangerouslySetInnerHTML={{
          __html: `
(function(){
  try {
    // Swap title
    var titleEl = document.querySelector('h1');
    if(titleEl) titleEl.textContent = ${JSON.stringify(article.title)};

    // Swap subtitle (first p after h1 in hero)
    var subtitleEl = document.querySelector('.hero-gradient .text-base.md\\\\:text-lg');
    if(subtitleEl) {
      ${article.subtitle ? `subtitleEl.textContent = ${JSON.stringify(article.subtitle)};` : 'subtitleEl.style.display = "none";'}
    }

    // Swap description lead paragraph
    var descEl = document.querySelector('.border-l-4.border-amber-400');
    if(descEl) descEl.textContent = ${JSON.stringify(article.description)};

    // Swap article body HTML
    var articleEl = document.querySelector('article.prose > div[dangerously-set-html], article.prose > div');
    if(articleEl) articleEl.innerHTML = ${JSON.stringify(article.body_html)};

    // Swap TOC
    var tocList = document.querySelector('nav ol.space-y-2');
    if(tocList) {
      var sections = ${JSON.stringify(sections)};
      var items = tocList.querySelectorAll('li');
      sections.forEach(function(sec, i) {
        if(items[i]) {
          var a = items[i].querySelector('a');
          if(a) a.textContent = (i+1) + '. ' + sec.title;
        }
      });
    }

    // Swap FAQ accordion
    var faqSection = document.querySelector('#faq');
    if(faqSection) {
      var faqs = ${JSON.stringify(article.faqs || [])};
      var details = faqSection.querySelectorAll('details');
      faqs.forEach(function(faq, i) {
        if(details[i]) {
          var summary = details[i].querySelector('summary span:first-child');
          if(summary) summary.textContent = faq.question;
          var answer = details[i].querySelector('.px-5.pb-5 p');
          if(answer) answer.textContent = faq.answer;
        }
      });
    }

    // Update date
    var dateEls = document.querySelectorAll('[data-date-field]');
    dateEls.forEach(function(el) {
      var field = el.getAttribute('data-date-field');
      if(field === 'published_at' && ${JSON.stringify(article.published_at || null)}) {
        el.textContent = new Date(${JSON.stringify(article.published_at || '')}).toLocaleDateString(${JSON.stringify(lc.dateLocale)});
      }
      if(field === 'updated_at') {
        el.textContent = new Date(${JSON.stringify(article.updated_at)}).toLocaleDateString(${JSON.stringify(lc.dateLocale)});
      }
    });
  } catch(e) {
    // Fail silently — zh version remains visible
    console.warn('LangAwareContent swap error:', e);
  }
})();
`,
        }}
      />
    </>
  )
}
