import { supabase } from '@/lib/supabase'
import { notFound } from 'next/navigation'
import type { Metadata } from 'next'
import type { InsightArticle } from '@/lib/types'
import ComparisonTable from '../ComparisonTable'

export const revalidate = 3600

interface PageProps {
  params: Promise<{ slug: string }>
  searchParams: Promise<{ lang?: string }>
}

const siteUrl = (process.env.NEXT_PUBLIC_SITE_URL || 'https://cloudpipe-macao-app.vercel.app').trim()

const VALID_LANGS = ['zh', 'en', 'pt'] as const
type Lang = (typeof VALID_LANGS)[number]

const LANG_CONFIG: Record<Lang, { label: string; locale: string; hreflang: string; inLanguage: string; dateLocale: string }> = {
  zh: { label: '中文', locale: 'zh_TW', hreflang: 'zh-Hant', inLanguage: 'zh-Hant', dateLocale: 'zh-TW' },
  en: { label: 'English', locale: 'en_US', hreflang: 'en', inLanguage: 'en', dateLocale: 'en-US' },
  pt: { label: 'Português', locale: 'pt_PT', hreflang: 'pt', inLanguage: 'pt', dateLocale: 'pt-PT' },
}

const UI_STRINGS: Record<Lang, {
  toc: string; faq: string; faqToc: string; sources: string; related: string
  comparison: string; back: string; backLabel: string; generatedBy: string; lastUpdated: string
  words: string; readTime: string; notFound: string
}> = {
  zh: {
    toc: '目錄', faq: '常見問題', faqToc: '常見問題 FAQ', sources: '資料來源',
    related: '相關商戶', comparison: '綜合比較表', back: '← 返回深度分析',
    backLabel: '深度分析', generatedBy: '由 CloudPipe AI 自動生成並人工審核',
    lastUpdated: '最後更新', words: '字', readTime: '分鐘', notFound: '找不到文章',
  },
  en: {
    toc: 'Table of Contents', faq: 'FAQ', faqToc: 'Frequently Asked Questions', sources: 'Sources',
    related: 'Related Merchants', comparison: 'Comparison Table', back: '← Back to Insights',
    backLabel: 'Insights', generatedBy: 'Auto-generated by CloudPipe AI with human review',
    lastUpdated: 'Last updated', words: 'words', readTime: 'min read', notFound: 'Article not found',
  },
  pt: {
    toc: 'Índice', faq: 'Perguntas Frequentes', faqToc: 'Perguntas Frequentes', sources: 'Fontes',
    related: 'Comerciantes Relacionados', comparison: 'Tabela Comparativa', back: '← Voltar às Análises',
    backLabel: 'Análises', generatedBy: 'Gerado automaticamente por CloudPipe AI com revisão humana',
    lastUpdated: 'Última atualização', words: 'palavras', readTime: 'min de leitura', notFound: 'Artigo não encontrado',
  },
}

function parseLang(raw?: string): Lang {
  if (raw && VALID_LANGS.includes(raw as Lang)) return raw as Lang
  return 'zh'
}

async function getInsight(slug: string, lang: Lang) {
  const { data } = await supabase
    .from('insights')
    .select('*')
    .eq('slug', slug)
    .eq('lang', lang)
    .eq('status', 'published')
    .single()
  return data as InsightArticle | null
}

async function getAvailableLangs(slug: string): Promise<Lang[]> {
  const { data } = await supabase
    .from('insights')
    .select('lang')
    .eq('slug', slug)
    .eq('status', 'published')
  if (!data) return []
  return data.map(d => d.lang as Lang).filter(l => VALID_LANGS.includes(l))
}

interface RelatedMerchant {
  slug: string
  name_zh: string
  name_en?: string
  district?: string
  google_rating?: number
  category: { slug: string; name_zh: string; icon?: string } | null
}

async function getRelatedMerchants(slugs: string[]): Promise<RelatedMerchant[]> {
  if (!slugs?.length) return []
  const { data } = await supabase
    .from('merchants')
    .select('slug, name_zh, name_en, category:categories(slug, name_zh, icon), district, google_rating')
    .in('slug', slugs)
    .eq('status', 'live')
  if (!data) return []
  return data.map((d: Record<string, unknown>) => ({
    ...d,
    category: Array.isArray(d.category) ? d.category[0] || null : d.category,
  })) as RelatedMerchant[]
}

export async function generateStaticParams() {
  const { data } = await supabase
    .from('insights')
    .select('slug')
    .eq('status', 'published')
  // Deduplicate slugs (multiple langs share same slug)
  const slugs = [...new Set((data || []).map(d => d.slug))]
  return slugs.map(slug => ({ slug }))
}

export async function generateMetadata({ params, searchParams }: PageProps): Promise<Metadata> {
  const { slug } = await params
  const { lang: langParam } = await searchParams
  const lang = parseLang(langParam)
  const lc = LANG_CONFIG[lang]

  const article = await getInsight(slug, lang)
  if (!article) return { title: UI_STRINGS[lang].notFound }

  const title = article.og_title || `${article.title} — CloudPipe AI`
  const description = article.og_description || article.description
  const availableLangs = await getAvailableLangs(slug)

  const alternates: Record<string, string> = {}
  for (const al of availableLangs) {
    const url = al === 'zh'
      ? `${siteUrl}/macao/insights/${slug}`
      : `${siteUrl}/macao/insights/${slug}?lang=${al}`
    alternates[LANG_CONFIG[al].hreflang] = url
  }

  return {
    title,
    description,
    openGraph: {
      title,
      description,
      type: 'article',
      locale: lc.locale,
      publishedTime: article.published_at || undefined,
      images: article.og_image ? [article.og_image] : undefined,
    },
    alternates: {
      canonical: lang === 'zh' ? `${siteUrl}/macao/insights/${slug}` : `${siteUrl}/macao/insights/${slug}?lang=${lang}`,
      languages: alternates,
    },
    other: { 'llms-txt': '/macao/llms-txt' },
  }
}

/* ── CATEGORY_TO_INDUSTRY mapping for merchant links ── */
const CATEGORY_TO_INDUSTRY: Record<string, string> = {
  restaurant: 'dining', japanese: 'dining', portuguese: 'dining',
  chinese: 'dining', western: 'dining', cafe: 'dining', bakery: 'dining',
  'food-import': 'food-trade', 'food-delivery': 'food-trade',
  hotel: 'hotels', resort: 'hotels',
  tourism: 'attractions', museum: 'attractions',
  retail: 'shopping', 'shopping-mall': 'shopping',
  beauty: 'wellness', gym: 'wellness',
  bar: 'nightlife', entertainment: 'gaming',
}

export default async function InsightDetailPage({ params, searchParams }: PageProps) {
  const { slug } = await params
  const { lang: langParam } = await searchParams
  const lang = parseLang(langParam)
  const ui = UI_STRINGS[lang]
  const lc = LANG_CONFIG[lang]

  const [article, availableLangs] = await Promise.all([
    getInsight(slug, lang),
    getAvailableLangs(slug),
  ])
  if (!article) notFound()

  const merchants = await getRelatedMerchants(article.related_merchant_slugs || [])

  /* ── Schema.org ── */
  const articleSchema = {
    '@context': 'https://schema.org',
    '@type': 'Article',
    headline: article.title,
    description: article.description,
    datePublished: article.published_at || article.created_at,
    dateModified: article.updated_at,
    wordCount: article.word_count,
    author: { '@type': 'Organization', name: 'CloudPipe AI', url: 'https://cloudpipe-landing.vercel.app' },
    publisher: { '@type': 'Organization', name: 'CloudPipe AI', url: 'https://cloudpipe-landing.vercel.app' },
    mainEntityOfPage: { '@type': 'WebPage', '@id': `${siteUrl}/macao/insights/${slug}` },
    articleSection: ui.backLabel,
    inLanguage: lc.inLanguage,
    ...(article.og_image && { image: article.og_image }),
  }

  const faqSchema = article.faqs?.length > 0 ? {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: article.faqs.map(f => ({
      '@type': 'Question',
      name: f.question,
      acceptedAnswer: { '@type': 'Answer', text: f.answer },
    })),
  } : null

  const breadcrumbSchema = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: 'CloudPipe AI', item: siteUrl },
      { '@type': 'ListItem', position: 2, name: lang === 'zh' ? '澳門商戶百科' : 'Macao Directory', item: `${siteUrl}/macao` },
      { '@type': 'ListItem', position: 3, name: ui.backLabel, item: `${siteUrl}/macao/insights` },
      { '@type': 'ListItem', position: 4, name: article.title, item: `${siteUrl}/macao/insights/${slug}` },
    ],
  }

  const sections = article.sections || []

  function langUrl(targetLang: Lang) {
    return targetLang === 'zh'
      ? `/macao/insights/${slug}`
      : `/macao/insights/${slug}?lang=${targetLang}`
  }

  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(articleSchema) }} />
      {faqSchema && <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />}
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }} />
      {/* hreflang */}
      {availableLangs.map(al => (
        <link key={al} rel="alternate" hrefLang={LANG_CONFIG[al].hreflang} href={`${siteUrl}${langUrl(al)}`} />
      ))}

      {/* ═══ Hero ═══ */}
      <div className="hero-gradient text-white">
        <div className="max-w-4xl mx-auto px-4 py-10">
          <nav className="text-sm text-blue-200/70 mb-4">
            <a href="/macao" className="hover:text-white transition-colors">{lang === 'zh' ? '澳門百科' : 'Macao'}</a>
            <span className="mx-2">/</span>
            <a href="/macao/insights" className="hover:text-white transition-colors">{ui.backLabel}</a>
            <span className="mx-2">/</span>
            <span className="text-white">{article.title}</span>
          </nav>

          <h1 className="text-2xl md:text-4xl font-bold mb-3 leading-tight">{article.title}</h1>
          {article.subtitle && <p className="text-base md:text-lg text-blue-100 mb-4">{article.subtitle}</p>}

          <div className="flex flex-wrap gap-2 mt-4">
            <span className="text-xs px-3 py-1.5 bg-white/15 backdrop-blur rounded-full border border-white/20">
              {article.word_count.toLocaleString()} {ui.words}
            </span>
            <span className="text-xs px-3 py-1.5 bg-white/15 backdrop-blur rounded-full border border-white/20">
              {article.read_time_minutes} {ui.readTime}
            </span>
            {article.published_at && (
              <span className="text-xs px-3 py-1.5 bg-white/15 backdrop-blur rounded-full border border-white/20">
                {new Date(article.published_at).toLocaleDateString(lc.dateLocale)}
              </span>
            )}
            {(article.tags || []).slice(0, 3).map(tag => (
              <span key={tag} className="text-xs px-3 py-1.5 bg-amber-400/90 text-white rounded-full font-semibold">
                {tag}
              </span>
            ))}
          </div>

          {/* ═══ Language Switcher ═══ */}
          {availableLangs.length > 1 && (
            <div className="flex gap-2 mt-5">
              {availableLangs.map(al => (
                <a
                  key={al}
                  href={langUrl(al)}
                  className={`text-xs px-3 py-1.5 rounded-full border transition-colors ${
                    al === lang
                      ? 'bg-white text-[#0f4c81] border-white font-bold'
                      : 'bg-white/10 text-white/80 border-white/30 hover:bg-white/20'
                  }`}
                >
                  {LANG_CONFIG[al].label}
                </a>
              ))}
            </div>
          )}
        </div>
      </div>
      <div className="gold-line"></div>

      <main className="max-w-4xl mx-auto px-4 py-10">
        {/* ═══ Table of Contents ═══ */}
        {sections.length > 0 && (
          <nav className="bg-white border border-gray-200 rounded-xl p-6 mb-10 shadow-sm">
            <h2 className="text-lg font-bold text-[#0f4c81] mb-4 flex items-center gap-2">
              <span className="w-1 h-6 bg-[#0f4c81] rounded-full inline-block"></span>
              {ui.toc}
            </h2>
            <ol className="space-y-2 text-sm">
              {sections.map((sec, i) => (
                <li key={sec.id}>
                  <a href={`#${sec.id}`} className="text-[#0f4c81] hover:underline">
                    {i + 1}. {sec.title}
                  </a>
                </li>
              ))}
              {(article.faqs?.length || 0) > 0 && (
                <li>
                  <a href="#faq" className="text-[#0f4c81] hover:underline">
                    {sections.length + 1}. {ui.faqToc}
                  </a>
                </li>
              )}
            </ol>
          </nav>
        )}

        {/* ═══ Article Body ═══ */}
        <article className="prose max-w-none mb-10">
          <div dangerouslySetInnerHTML={{ __html: article.body_html }} />
        </article>

        {/* ═══ Comparison Table ═══ */}
        {article.table_data && (
          <section className="mb-10">
            <h2 className="text-xl font-bold text-[#0f4c81] mb-6 flex items-center gap-2">
              <span className="w-1 h-6 bg-[#0f4c81] rounded-full inline-block"></span>
              {ui.comparison}
            </h2>
            <ComparisonTable data={article.table_data} />
          </section>
        )}

        {/* ═══ FAQ ═══ */}
        {article.faqs?.length > 0 && (
          <section id="faq" className="mb-10">
            <h2 className="text-xl font-bold text-[#0f4c81] mb-6 flex items-center gap-2">
              <span className="w-1 h-6 bg-[#0f4c81] rounded-full inline-block"></span>
              {ui.faq}
            </h2>
            <div className="space-y-3">
              {article.faqs.map((faq, i) => (
                <details key={i} className="bg-white border border-gray-200 rounded-xl overflow-hidden group">
                  <summary className="font-semibold cursor-pointer p-5 flex justify-between items-center hover:bg-gray-50 transition-colors text-[#1a1a2e]">
                    <span className="pr-4">{faq.question}</span>
                    <span className="text-[#0f4c81] text-sm group-open:rotate-180 transition-transform flex-shrink-0">▼</span>
                  </summary>
                  <div className="px-5 pb-5 border-t border-gray-100">
                    <p className="mt-4 text-gray-600 leading-relaxed">{faq.answer}</p>
                  </div>
                </details>
              ))}
            </div>
          </section>
        )}

        {/* ═══ Authority Sources ═══ */}
        {(article.authority_sources?.length || 0) > 0 && (
          <section className="mb-10">
            <h2 className="text-lg font-bold text-[#0f4c81] mb-4 flex items-center gap-2">
              <span className="w-1 h-6 bg-[#0f4c81] rounded-full inline-block"></span>
              {ui.sources}
            </h2>
            <ul className="space-y-2 text-sm text-gray-600">
              {article.authority_sources!.map((src, i) => (
                <li key={i} className="flex items-start gap-2">
                  <span className="text-[#0f4c81] mt-0.5 flex-shrink-0">•</span>
                  <span>
                    <a href={src.url} target="_blank" rel="noopener noreferrer" className="text-[#0f4c81] hover:underline font-medium">
                      {src.name}
                    </a>
                    {src.stat && <span className="text-gray-400 ml-1">— {src.stat}</span>}
                  </span>
                </li>
              ))}
            </ul>
          </section>
        )}

        {/* ═══ Related Merchants ═══ */}
        {merchants.length > 0 && (
          <section className="mb-10">
            <h2 className="text-lg font-bold text-[#0f4c81] mb-4 flex items-center gap-2">
              <span className="w-1 h-6 bg-[#0f4c81] rounded-full inline-block"></span>
              {ui.related}
            </h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {merchants.map(m => {
                const indSlug = CATEGORY_TO_INDUSTRY[m.category?.slug || ''] || 'dining'
                return (
                  <a
                    key={m.slug}
                    href={`/macao/${indSlug}/${m.category?.slug || 'other'}/${m.slug}`}
                    className="card-hover block bg-white border border-gray-200 rounded-xl p-5"
                  >
                    <h3 className="font-semibold text-[#1a1a2e] mb-1">{m.name_zh}</h3>
                    {m.name_en && <p className="text-xs text-gray-400 mb-2">{m.name_en}</p>}
                    <div className="flex flex-wrap gap-1.5 text-xs">
                      {m.category?.name_zh && (
                        <span className="px-2 py-0.5 bg-[#e8f0fe] text-[#0f4c81] rounded font-medium">
                          {m.category.icon || '📋'} {m.category.name_zh}
                        </span>
                      )}
                      {m.google_rating && (
                        <span className="px-2 py-0.5 rating-badge rounded">★ {m.google_rating}</span>
                      )}
                      {m.district && (
                        <span className="px-2 py-0.5 bg-gray-100 text-gray-600 rounded">{m.district}</span>
                      )}
                    </div>
                  </a>
                )
              })}
            </div>
          </section>
        )}

        {/* ═══ Footer ═══ */}
        <footer className="border-t border-gray-200 pt-8 mt-10 text-sm text-gray-400">
          <div className="flex flex-col md:flex-row justify-between gap-2">
            <div>
              <p>{ui.generatedBy.split('CloudPipe AI')[0]}<a href="https://cloudpipe-landing.vercel.app" className="text-[#0f4c81] hover:underline">CloudPipe AI</a>{ui.generatedBy.split('CloudPipe AI')[1]}</p>
              <p className="mt-1">{ui.lastUpdated}：{new Date(article.updated_at).toLocaleDateString(lc.dateLocale)}</p>
            </div>
            <div className="text-right">
              <a href="/macao/insights" className="text-[#0f4c81] hover:underline">{ui.back}</a>
              <p className="mt-1">© 2026 CloudPipe AI · CC BY 4.0</p>
            </div>
          </div>
        </footer>
      </main>
    </>
  )
}
