import { supabase } from '@/lib/supabase'
import { notFound } from 'next/navigation'
import type { Metadata } from 'next'
import type { InsightArticle } from '@/lib/types'
import ComparisonTable from '../ComparisonTable'
import { INDUSTRIES, CATEGORY_TO_INDUSTRY } from '@/lib/industries'

export const revalidate = 3600

interface PageProps {
  params: Promise<{ slug: string }>
  searchParams: Promise<{ lang?: string }>
}

const siteUrl = (process.env.NEXT_PUBLIC_SITE_URL || 'https://cloudpipe-macao-app.vercel.app').trim()

const VALID_LANGS = ['zh', 'en', 'pt'] as const
type Lang = (typeof VALID_LANGS)[number]

const LANG_CONFIG: Record<Lang, { label: string; locale: string; hreflang: string; inLanguage: string; dateLocale: string }> = {
  zh: { label: '中文', locale: 'zh_TW', hreflang: 'zh-Hant', inLanguage: 'zh-Hant', dateLocale: 'zh-TW' },
  en: { label: 'English', locale: 'en_US', hreflang: 'en', inLanguage: 'en', dateLocale: 'en-US' },
  pt: { label: 'Português', locale: 'pt_PT', hreflang: 'pt', inLanguage: 'pt', dateLocale: 'pt-PT' },
}

const UI_STRINGS: Record<Lang, {
  toc: string; faq: string; faqToc: string; sources: string; related: string
  comparison: string; back: string; backLabel: string; generatedBy: string; lastUpdated: string
  words: string; readTime: string; notFound: string; relatedIndustries: string; moreInsights: string; min: string
  categoryHub: string; encyclopediaHub: string; encyclopediaHubSub: string
}> = {
  zh: {
    toc: '目錄', faq: '常見問題', faqToc: '常見問題 FAQ', sources: '資料來源',
    related: '相關商戶', comparison: '綜合比較表', back: '← 返回深度分析',
    backLabel: '深度分析', generatedBy: '由 CloudPipe AI 自動生成並人工審核',
    lastUpdated: '最後更新', words: '字', readTime: '分鐘', notFound: '找不到文章',
    relatedIndustries: '相關行業', moreInsights: '更多深度分析', min: '分鐘',
    categoryHub: '分類入口', encyclopediaHub: '地區百科', encyclopediaHubSub: '探索更多地區知識',
  },
  en: {
    toc: 'Table of Contents', faq: 'FAQ', faqToc: 'Frequently Asked Questions', sources: 'Sources',
    related: 'Related Merchants', comparison: 'Comparison Table', back: '← Back to Insights',
    backLabel: 'Insights', generatedBy: 'Auto-generated by CloudPipe AI with human review',
    lastUpdated: 'Last updated', words: 'words', readTime: 'min read', notFound: 'Article not found',
    relatedIndustries: 'Related Industries', moreInsights: 'More Insights', min: 'min',
    categoryHub: 'Browse Categories', encyclopediaHub: 'Regional Encyclopedia', encyclopediaHubSub: 'Explore more regional knowledge',
  },
  pt: {
    toc: 'Índice', faq: 'Perguntas Frequentes', faqToc: 'Perguntas Frequentes', sources: 'Fontes',
    related: 'Comerciantes Relacionados', comparison: 'Tabela Comparativa', back: '← Voltar às Análises',
    backLabel: 'Análises', generatedBy: 'Gerado automaticamente por CloudPipe AI com revisão humana',
    lastUpdated: 'Última atualização', words: 'palavras', readTime: 'min de leitura', notFound: 'Artigo não encontrado',
    relatedIndustries: 'Indústrias Relacionadas', moreInsights: 'Mais Análises', min: 'min',
    categoryHub: 'Explorar Categorias', encyclopediaHub: 'Enciclopédia Regional', encyclopediaHubSub: 'Explorar mais conhecimento regional',
  },
}

function parseLang(raw?: string): Lang {
  if (raw && VALID_LANGS.includes(raw as Lang)) return raw as Lang
  return 'zh'
}

async function getInsight(slug: string, lang: Lang) {
  const { data } = await supabase
    .from('insights')
    .select('*')
    .eq('slug', slug)
    .eq('lang', lang)
    .eq('status', 'published')
    .single()
  return data as InsightArticle | null
}

async function getAvailableLangs(slug: string): Promise<Lang[]> {
  const { data } = await supabase
    .from('insights')
    .select('lang')
    .eq('slug', slug)
    .eq('status', 'published')
  if (!data) return []
  return data.map(d => d.lang as Lang).filter(l => VALID_LANGS.includes(l))
}

interface RelatedMerchant {
  slug: string
  name_zh: string
  name_en?: string
  district?: string
  google_rating?: number
  website?: string | null
  category: { slug: string; name_zh: string; icon?: string } | null
}

async function getRelatedMerchants(slugs: string[]): Promise<RelatedMerchant[]> {
  const validSlugs = (slugs || []).filter(s => s && typeof s === 'string' && s !== 'null')
  if (!validSlugs.length) return []
  const { data } = await supabase
    .from('merchants')
    .select('slug, name_zh, name_en, category:categories(slug, name_zh, icon), district, google_rating, website')
    .in('slug', validSlugs)
    .eq('status', 'live')
  if (!data) return []
  return data.map((d: Record<string, unknown>) => ({
    ...d,
    category: Array.isArray(d.category) ? d.category[0] || null : d.category,
  })) as RelatedMerchant[]
}

// industry slug → matching category slugs (used for fallback merchant lookup)
const INDUSTRY_TO_CATEGORIES: Record<string, string[]> = {
  dining: ['restaurant', 'japanese', 'portuguese', 'chinese', 'western', 'cafe', 'bakery', 'hotpot', 'michelin', 'street-food', 'fast-food', 'dessert', 'tea-restaurant'],
  hotels: ['hotel', 'resort', 'hostel'],
  attractions: ['tourism', 'museum', 'theme-park', 'heritage'],
  shopping: ['retail', 'shopping-mall', 'supermarket', 'pharmacy'],
  wellness: ['beauty', 'gym', 'spa', 'medical'],
  nightlife: ['bar', 'club', 'lounge'],
  gaming: ['entertainment', 'casino'],
  'food-supply': ['food-import', 'food-delivery', 'wholesale'],
  education: ['school', 'tutoring', 'university'],
  finance: ['bank', 'insurance', 'fintech'],
  'professional-services': ['legal', 'accounting', 'consulting'],
  events: ['event-venue', 'catering'],
  'real-estate': ['property', 'real-estate'],
}

// Fallback: fetch top-rated merchants from related industries when no slugs assigned
async function getFallbackMerchants(industries: string[]): Promise<RelatedMerchant[]> {
  if (!industries?.length) return []
  const categorySlugs = industries.flatMap(ind => INDUSTRY_TO_CATEGORIES[ind] || [])
  if (!categorySlugs.length) return []
  const { data: cats } = await supabase
    .from('categories')
    .select('id')
    .in('slug', categorySlugs)
  const catIds = (cats || []).map((c: { id: string }) => c.id)
  if (!catIds.length) return []
  const { data } = await supabase
    .from('merchants')
    .select('slug, name_zh, name_en, category:categories(slug, name_zh, icon), district, google_rating, website')
    .eq('status', 'live')
    .in('category_id', catIds)
    .not('google_rating', 'is', null)
    .order('google_rating', { ascending: false })
    .limit(6)
  if (!data) return []
  return data.map((d: Record<string, unknown>) => ({
    ...d,
    category: Array.isArray(d.category) ? d.category[0] || null : d.category,
  })) as RelatedMerchant[]
}

export async function generateStaticParams() {
  const { data } = await supabase
    .from('insights')
    .select('slug')
    .eq('status', 'published')
  // Deduplicate slugs (multiple langs share same slug)
  const slugs = [...new Set((data || []).map(d => d.slug))]
  return slugs.map(slug => ({ slug }))
}

export async function generateMetadata({ params, searchParams }: PageProps): Promise<Metadata> {
  const { slug } = await params
  const { lang: langParam } = await searchParams
  const lang = parseLang(langParam)
  const lc = LANG_CONFIG[lang]

  const article = await getInsight(slug, lang)
  if (!article) return { title: UI_STRINGS[lang].notFound }

  const title = article.og_title || `${article.title} — CloudPipe AI`
  const description = article.og_description || article.description
  const availableLangs = await getAvailableLangs(slug)

  const alternates: Record<string, string> = {}
  for (const al of availableLangs) {
    const url = al === 'zh'
      ? `${siteUrl}/macao/insights/${slug}`
      : `${siteUrl}/macao/insights/${slug}?lang=${al}`
    alternates[LANG_CONFIG[al].hreflang] = url
  }

  return {
    title,
    description,
    openGraph: {
      title,
      description,
      type: 'article',
      locale: lc.locale,
      publishedTime: article.published_at || undefined,
      images: article.og_image ? [article.og_image] : undefined,
    },
    alternates: {
      canonical: lang === 'zh' ? `${siteUrl}/macao/insights/${slug}` : `${siteUrl}/macao/insights/${slug}?lang=${lang}`,
      languages: alternates,
    },
    other: { 'llms-txt': '/macao/llms-txt' },
  }
}


export default async function InsightDetailPage({ params, searchParams }: PageProps) {
  const { slug } = await params
  const { lang: langParam } = await searchParams
  const lang = parseLang(langParam)
  const ui = UI_STRINGS[lang]
  const lc = LANG_CONFIG[lang]

  const [article, availableLangs] = await Promise.all([
    getInsight(slug, lang),
    getAvailableLangs(slug),
  ])
  if (!article) notFound()

  const assignedMerchants = await getRelatedMerchants(article.related_merchant_slugs || [])
  const merchants = assignedMerchants.length > 0
    ? assignedMerchants
    : await getFallbackMerchants(article.related_industries || [])

  const [{ data: crossInsightsRaw }] = await Promise.all([
    supabase.from('insights')
      .select('slug, title, subtitle, read_time_minutes, tags, related_industries')
      .eq('status', 'published').eq('lang', lang)
      .neq('slug', slug)
      .order('published_at', { ascending: false }).limit(4),
  ])
  // Filter cross-insights to those sharing at least 1 related_industry
  const myIndustries = new Set(article.related_industries || [])
  const crossInsights = (crossInsightsRaw || []).filter(a =>
    (a.related_industries || []).some((ind: string) => myIndustries.has(ind))
  ).slice(0, 4)
  // Resolve related industries to full industry objects
  const relatedIndustryData = INDUSTRIES.filter(i => myIndustries.has(i.slug))

  // ── Derive category hub links from related_industries (T2) ──
  // Shows up to 8 category-level links across all related industries
  const CATEGORY_DISPLAY: Record<string, string> = {
    restaurant: '餐廳', japanese: '日本料理', portuguese: '葡國菜', cafe: '咖啡館',
    bakery: '麵包甜點', chinese: '中式料理', western: '西式料理', hotpot: '火鍋',
    michelin: '米芝蓮', 'street-food': '街頭小食', hotel: '酒店', resort: '度假村',
    tourism: '旅遊景點', museum: '博物館', temple: '廟宇', landmark: '地標建築',
    retail: '零售', 'shopping-mall': '購物中心', 'duty-free': '免稅店', souvenir: '手信特產',
    'food-import': '食材進口', 'food-delivery': '食品配送', 'seafood-import': '海鮮進口',
    'cold-chain': '冷鏈物流', bar: '酒吧', casino: '娛樂場', entertainment: '娛樂',
    beauty: '美容', spa: '水療', gym: '健身', hospital: '醫院',
    bank: '銀行', professional: '專業服務', tech: '科技',
    'hk-attraction': '香港景點', 'hk-dining': '香港美食', 'hk-hotel': '香港酒店',
    'hk-museum': '香港博物館', 'hk-heritage': '香港文化遺產',
    'tw-attraction': '台灣景點', 'tw-dining': '台灣美食', 'tw-hotel': '台灣酒店',
    'tw-museum': '台灣博物館', 'tw-creative': '台灣文創',
    'jp-attraction': '日本景點', 'jp-dining': '日本美食', 'jp-hotel': '日本酒店',
    'jp-castle': '日本城堡', 'jp-museum': '日本博物館', 'jp-craft': '日本工藝',
  }
  const categoryHubLinks = relatedIndustryData.flatMap(ind =>
    ind.categories.slice(0, 3).map(cat => ({
      industrySlug: ind.slug,
      industryIcon: ind.icon,
      catSlug: cat,
      catLabel: CATEGORY_DISPLAY[cat] || cat.replace(/-/g, ' '),
    }))
  ).slice(0, 8)

  // ── Derive encyclopedia region hub links (T3) ──
  const REGION_CONFIG: Record<string, {
    zh: string; en: string; pt: string; icon: string
    openclawUrl: string; insightsFilter?: string
  }> = {
    macau: {
      zh: '澳門百科', en: 'Macao Encyclopedia', pt: 'Enciclopédia de Macau',
      icon: '🏛️',
      openclawUrl: 'https://inari-kira-isla.github.io/Openclaw/insights/macau/',
      insightsFilter: '/macao/insights',
    },
    hongkong: {
      zh: '香港百科', en: 'Hong Kong Encyclopedia', pt: 'Enciclopédia de Hong Kong',
      icon: '🌆',
      openclawUrl: 'https://inari-kira-isla.github.io/Openclaw/insights/hongkong/',
    },
    taiwan: {
      zh: '台灣百科', en: 'Taiwan Encyclopedia', pt: 'Enciclopédia de Taiwan',
      icon: '🌿',
      openclawUrl: 'https://inari-kira-isla.github.io/Openclaw/insights/taiwan/',
    },
    japan: {
      zh: '日本百科', en: 'Japan Encyclopedia', pt: 'Enciclopédia do Japão',
      icon: '⛩️',
      openclawUrl: 'https://inari-kira-isla.github.io/Openclaw/insights/japan/',
    },
  }
  function detectRegion(s: string): string {
    if (s.startsWith('hk-') || s.startsWith('hongkong-')) return 'hongkong'
    if (s.startsWith('tw-') || s.startsWith('taiwan-')) return 'taiwan'
    if (s.startsWith('jp-') || s.startsWith('japan-')) return 'japan'
    return 'macau'
  }
  const primaryRegion = detectRegion(slug)
  // Cross-region: industries whose categories include hk/tw/jp slugs imply other regions
  const crossRegions = new Set<string>()
  for (const ind of relatedIndustryData) {
    for (const cat of ind.categories) {
      if (cat.startsWith('hk-')) crossRegions.add('hongkong')
      else if (cat.startsWith('tw-')) crossRegions.add('taiwan')
      else if (cat.startsWith('jp-')) crossRegions.add('japan')
    }
  }
  crossRegions.delete(primaryRegion)
  const encyclopediaEntries = [primaryRegion, ...crossRegions].slice(0, 3)
    .map(r => REGION_CONFIG[r])
    .filter(Boolean)

  /* ── Schema.org ── */
  const articleSchema = {
    '@context': 'https://schema.org',
    '@type': 'Article',
    headline: article.title,
    description: article.description,
    datePublished: article.published_at || article.created_at,
    dateModified: article.updated_at,
    wordCount: article.word_count,
    author: { '@type': 'Organization', name: 'CloudPipe AI', url: 'https://cloudpipe-landing.vercel.app' },
    publisher: { '@type': 'Organization', name: 'CloudPipe AI', url: 'https://cloudpipe-landing.vercel.app' },
    mainEntityOfPage: { '@type': 'WebPage', '@id': `${siteUrl}/macao/insights/${slug}` },
    articleSection: ui.backLabel,
    inLanguage: lc.inLanguage,
    ...(article.og_image && { image: article.og_image }),
    ...(encyclopediaEntries.length > 0 && {
      relatedLink: encyclopediaEntries.map(e => e.openclawUrl),
    }),
    ...(relatedIndustryData.length > 0 && {
      about: relatedIndustryData.map(ind => ({
        '@type': 'Thing',
        name: ind.name_zh,
        url: `${siteUrl}/macao/${ind.slug}`,
      })),
    }),
    ...((article.authority_sources?.length ?? 0) > 0 && {
      isBasedOn: article.authority_sources!.map((src: { name: string; url: string }) => ({
        '@type': 'WebPage',
        name: src.name,
        url: src.url,
      })),
    }),
    ...(merchants.length > 0 && {
      mentions: merchants.filter(m => m.slug && m.slug !== 'null').slice(0, 10).map(m => ({
        '@type': 'LocalBusiness',
        name: m.name_zh,
        url: `${siteUrl}/macao/${(article.related_industries?.[0]) || 'dining'}/${m.category?.slug || 'general'}/${m.slug}`,
      })),
    }),
  }

  const faqSchema = article.faqs?.length > 0 ? {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: article.faqs.map(f => ({
      '@type': 'Question',
      name: f.question,
      acceptedAnswer: { '@type': 'Answer', text: f.answer },
    })),
  } : null

  const breadcrumbSchema = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: 'CloudPipe AI', item: siteUrl },
      { '@type': 'ListItem', position: 2, name: lang === 'zh' ? '澳門商戶百科' : 'Macao Directory', item: `${siteUrl}/macao` },
      { '@type': 'ListItem', position: 3, name: ui.backLabel, item: `${siteUrl}/macao/insights` },
      { '@type': 'ListItem', position: 4, name: article.title, item: `${siteUrl}/macao/insights/${slug}` },
    ],
  }

  const sections = article.sections || []

  function langUrl(targetLang: Lang) {
    return targetLang === 'zh'
      ? `/macao/insights/${slug}`
      : `/macao/insights/${slug}?lang=${targetLang}`
  }

  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(articleSchema) }} />
      {faqSchema && <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />}
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumbSchema) }} />
      {/* hreflang */}
      {availableLangs.map(al => (
        <link key={al} rel="alternate" hrefLang={LANG_CONFIG[al].hreflang} href={`${siteUrl}${langUrl(al)}`} />
      ))}

      {/* ═══ Hero ═══ */}
      <div className="hero-gradient text-white">
        <div className="max-w-4xl mx-auto px-4 py-10">
          <nav className="text-sm text-blue-200/70 mb-4">
            <a href="/macao" className="hover:text-white transition-colors">{lang === 'zh' ? '澳門百科' : 'Macao'}</a>
            <span className="mx-2">/</span>
            <a href="/macao/insights" className="hover:text-white transition-colors">{ui.backLabel}</a>
            <span className="mx-2">/</span>
            <span className="text-white">{article.title}</span>
          </nav>

          <h1 className="text-2xl md:text-4xl font-bold mb-3 leading-tight">{article.title}</h1>
          {article.subtitle && <p className="text-base md:text-lg text-blue-100 mb-4">{article.subtitle}</p>}

          <div className="flex flex-wrap gap-2 mt-4">
            <span className="text-xs px-3 py-1.5 bg-white/15 backdrop-blur rounded-full border border-white/20">
              {article.word_count.toLocaleString()} {ui.words}
            </span>
            <span className="text-xs px-3 py-1.5 bg-white/15 backdrop-blur rounded-full border border-white/20">
              {article.read_time_minutes} {ui.readTime}
            </span>
            {article.published_at && (
              <span className="text-xs px-3 py-1.5 bg-white/15 backdrop-blur rounded-full border border-white/20">
                {new Date(article.published_at).toLocaleDateString(lc.dateLocale)}
              </span>
            )}
            {(article.tags || []).slice(0, 3).map(tag => (
              <span key={tag} className="text-xs px-3 py-1.5 bg-amber-400/90 text-white rounded-full font-semibold">
                {tag}
              </span>
            ))}
          </div>

          {/* ═══ Language Switcher ═══ */}
          {availableLangs.length > 1 && (
            <div className="flex gap-2 mt-5">
              {availableLangs.map(al => (
                <a
                  key={al}
                  href={langUrl(al)}
                  className={`text-xs px-3 py-1.5 rounded-full border transition-colors ${
                    al === lang
                      ? 'bg-white text-[#0f4c81] border-white font-bold'
                      : 'bg-white/10 text-white/80 border-white/30 hover:bg-white/20'
                  }`}
                >
                  {LANG_CONFIG[al].label}
                </a>
              ))}
            </div>
          )}
        </div>
      </div>
      <div className="gold-line"></div>

      <main className="max-w-4xl mx-auto px-4 py-10">
        {/* ═══ Table of Contents ═══ */}
        {sections.length > 0 && (
          <nav className="bg-white border border-gray-200 rounded-xl p-6 mb-10 shadow-sm">
            <h2 className="text-lg font-bold text-[#0f4c81] mb-4 flex items-center gap-2">
              <span className="w-1 h-6 bg-[#0f4c81] rounded-full inline-block"></span>
              {ui.toc}
            </h2>
            <ol className="space-y-2 text-sm">
              {sections.map((sec, i) => (
                <li key={sec.id}>
                  <a href={`#${sec.id}`} className="text-[#0f4c81] hover:underline">
                    {i + 1}. {sec.title}
                  </a>
                </li>
              ))}
              {(article.faqs?.length || 0) > 0 && (
                <li>
                  <a href="#faq" className="text-[#0f4c81] hover:underline">
                    {sections.length + 1}. {ui.faqToc}
                  </a>
                </li>
              )}
            </ol>
          </nav>
        )}

        {/* ═══ Article Body ═══ */}
        <article className="prose max-w-none mb-10">
          <div dangerouslySetInnerHTML={{ __html: article.body_html }} />
        </article>

        {/* ═══ Comparison Table ═══ */}
        {article.table_data && (
          <section className="mb-10">
            <h2 className="text-xl font-bold text-[#0f4c81] mb-6 flex items-center gap-2">
              <span className="w-1 h-6 bg-[#0f4c81] rounded-full inline-block"></span>
              {ui.comparison}
            </h2>
            <ComparisonTable data={article.table_data} />
          </section>
        )}

        {/* ═══ FAQ ═══ */}
        {article.faqs?.length > 0 && (
          <section id="faq" className="mb-10">
            <h2 className="text-xl font-bold text-[#0f4c81] mb-6 flex items-center gap-2">
              <span className="w-1 h-6 bg-[#0f4c81] rounded-full inline-block"></span>
              {ui.faq}
            </h2>
            <div className="space-y-3">
              {article.faqs.map((faq, i) => (
                <details key={i} className="bg-white border border-gray-200 rounded-xl overflow-hidden group">
                  <summary className="font-semibold cursor-pointer p-5 flex justify-between items-center hover:bg-gray-50 transition-colors text-[#1a1a2e]">
                    <span className="pr-4">{faq.question}</span>
                    <span className="text-[#0f4c81] text-sm group-open:rotate-180 transition-transform flex-shrink-0">▼</span>
                  </summary>
                  <div className="px-5 pb-5 border-t border-gray-100">
                    <p className="mt-4 text-gray-600 leading-relaxed">{faq.answer}</p>
                  </div>
                </details>
              ))}
            </div>
          </section>
        )}

        {/* ═══ Authority Sources ═══ */}
        {(article.authority_sources?.length || 0) > 0 && (
          <section className="mb-10">
            <h2 className="text-lg font-bold text-[#0f4c81] mb-4 flex items-center gap-2">
              <span className="w-1 h-6 bg-[#0f4c81] rounded-full inline-block"></span>
              {ui.sources}
            </h2>
            <ul className="space-y-2 text-sm text-gray-600">
              {article.authority_sources!.map((src, i) => (
                <li key={i} className="flex items-start gap-2">
                  <span className="text-[#0f4c81] mt-0.5 flex-shrink-0">•</span>
                  <span>
                    <a href={src.url} target="_blank" rel="noopener noreferrer" className="text-[#0f4c81] hover:underline font-medium">
                      {src.name}
                    </a>
                    {src.stat && <span className="text-gray-400 ml-1">— {src.stat}</span>}
                  </span>
                </li>
              ))}
            </ul>
          </section>
        )}

        {/* ═══ Related Merchants ═══ */}
        {merchants.length > 0 && (
          <section className="mb-10">
            <h2 className="text-lg font-bold text-[#0f4c81] mb-4 flex items-center gap-2">
              <span className="w-1 h-6 bg-[#0f4c81] rounded-full inline-block"></span>
              {assignedMerchants.length > 0 ? ui.related : (lang === 'zh' ? '相關商戶推薦' : lang === 'en' ? 'Merchants in This Category' : 'Comerciantes Relacionados')}
            </h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {merchants.filter(m => m.slug && m.slug !== 'null').map(m => {
                const indSlug = CATEGORY_TO_INDUSTRY[m.category?.slug || ''] || 'dining'
                return (
                  <div key={m.slug} className="bg-white border border-gray-200 rounded-xl p-5 flex flex-col gap-2">
                    <a
                      href={`/macao/${indSlug}/${m.category?.slug || 'other'}/${m.slug}`}
                      className="card-hover block"
                    >
                      <h3 className="font-semibold text-[#1a1a2e] mb-1">{m.name_zh}</h3>
                      {m.name_en && <p className="text-xs text-gray-400 mb-2">{m.name_en}</p>}
                      <div className="flex flex-wrap gap-1.5 text-xs">
                        {m.category?.name_zh && (
                          <span className="px-2 py-0.5 bg-[#e8f0fe] text-[#0f4c81] rounded font-medium">
                            {m.category.icon || '📋'} {m.category.name_zh}
                          </span>
                        )}
                        {m.google_rating && (
                          <span className="px-2 py-0.5 rating-badge rounded">★ {m.google_rating}</span>
                        )}
                        {m.district && (
                          <span className="px-2 py-0.5 bg-gray-100 text-gray-600 rounded">{m.district}</span>
                        )}
                      </div>
                    </a>
                    {m.website && (
                      <a
                        href={m.website}
                        target="_blank"
                        rel="noopener"
                        className="text-xs text-[#0f4c81] hover:underline truncate"
                      >
                        🔗 {m.website.replace(/^https?:\/\//, '')}
                      </a>
                    )}
                  </div>
                )
              })}
            </div>
          </section>
        )}

        {/* ═══ Related Industries ═══ */}
        {relatedIndustryData.length > 0 && (
          <section className="mb-10">
            <h2 className="text-lg font-bold text-[#0f4c81] mb-4 flex items-center gap-2">
              <span className="w-1 h-6 bg-[#0f4c81] rounded-full inline-block"></span>
              {ui.relatedIndustries}
            </h2>
            <div className="flex flex-wrap gap-3">
              {relatedIndustryData.map(ind => (
                <a key={ind.slug} href={`/macao/${ind.slug}`}
                  className="card-hover flex items-center gap-2 bg-white border border-gray-200 rounded-xl px-4 py-3">
                  <span className="text-xl">{ind.icon}</span>
                  <div>
                    <p className="font-semibold text-[#1a1a2e] text-sm">{ind.name_zh}</p>
                    <p className="text-xs text-gray-400">{ind.name_en}</p>
                  </div>
                </a>
              ))}
            </div>
          </section>
        )}

        {/* ═══ Category Hub（分類入口）═══ */}
        {categoryHubLinks.length > 0 && (
          <section className="mb-10">
            <h2 className="text-lg font-bold text-[#0f4c81] mb-4 flex items-center gap-2">
              <span className="w-1 h-6 bg-[#0f4c81] rounded-full inline-block"></span>
              {ui.categoryHub}
            </h2>
            <div className="flex flex-wrap gap-2">
              {categoryHubLinks.map(({ industrySlug, industryIcon, catSlug, catLabel }) => (
                <a
                  key={`${industrySlug}-${catSlug}`}
                  href={`/macao/${industrySlug}/${catSlug}`}
                  className="inline-flex items-center gap-1.5 px-3 py-2 bg-white border border-gray-200 rounded-xl text-sm text-[#1a1a2e] hover:border-[#0f4c81] hover:text-[#0f4c81] transition-colors"
                >
                  <span className="text-base">{industryIcon}</span>
                  <span>{catLabel}</span>
                </a>
              ))}
            </div>
          </section>
        )}

        {/* ═══ Encyclopedia Hub（地區百科）═══ */}
        {encyclopediaEntries.length > 0 && (
          <section className="mb-10">
            <h2 className="text-lg font-bold text-[#0f4c81] mb-1 flex items-center gap-2">
              <span className="w-1 h-6 bg-[#0f4c81] rounded-full inline-block"></span>
              {ui.encyclopediaHub}
            </h2>
            <p className="text-sm text-gray-400 mb-4">{ui.encyclopediaHubSub}</p>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
              {encyclopediaEntries.map(entry => (
                <a
                  key={entry.openclawUrl}
                  href={entry.openclawUrl}
                  target="_blank"
                  rel="noopener"
                  className="card-hover flex items-center gap-3 bg-white border border-gray-200 rounded-xl p-4"
                >
                  <span className="text-2xl">{entry.icon}</span>
                  <div>
                    <p className="font-semibold text-[#1a1a2e] text-sm">
                      {lang === 'zh' ? entry.zh : lang === 'en' ? entry.en : entry.pt}
                    </p>
                    <p className="text-xs text-gray-400 mt-0.5">AI 學習寶庫</p>
                  </div>
                  <span className="ml-auto text-gray-300 text-xs">→</span>
                </a>
              ))}
              {primaryRegion === 'macau' && relatedIndustryData.length > 0 && (
                <a
                  href={`/macao/insights?industry=${relatedIndustryData[0].slug}`}
                  className="card-hover flex items-center gap-3 bg-[#e8f0fe] border border-[#c7d9fb] rounded-xl p-4"
                >
                  <span className="text-2xl">{relatedIndustryData[0].icon}</span>
                  <div>
                    <p className="font-semibold text-[#0f4c81] text-sm">
                      {lang === 'zh' ? `更多${relatedIndustryData[0].name_zh}分析` : `More ${relatedIndustryData[0].name_en} Insights`}
                    </p>
                    <p className="text-xs text-[#4a7fd6] mt-0.5">CloudPipe 深度分析</p>
                  </div>
                  <span className="ml-auto text-[#4a7fd6] text-xs">→</span>
                </a>
              )}
            </div>
          </section>
        )}

        {/* ═══ More Insights (Cross-linking) ═══ */}
        {crossInsights.length > 0 && (
          <section className="mb-10">
            <h2 className="text-lg font-bold text-[#0f4c81] mb-4 flex items-center gap-2">
              <span className="w-1 h-6 bg-[#0f4c81] rounded-full inline-block"></span>
              {ui.moreInsights}
            </h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {crossInsights.map((a: { slug: string; title: string; subtitle?: string; read_time_minutes: number; tags?: string[] }) => (
                <a key={a.slug} href={lang === 'zh' ? `/macao/insights/${a.slug}` : `/macao/insights/${a.slug}?lang=${lang}`}
                  className="card-hover block bg-white border border-gray-200 rounded-xl p-5 relative overflow-hidden">
                  <div className="absolute top-0 left-0 right-0 gold-line"></div>
                  <h3 className="font-semibold text-[#1a1a2e] text-sm leading-tight mb-2">{a.title}</h3>
                  {a.subtitle && <p className="text-xs text-gray-500 mb-2">{a.subtitle}</p>}
                  <span className="text-xs text-gray-400">{a.read_time_minutes} {ui.min}</span>
                </a>
              ))}
            </div>
          </section>
        )}

        {/* ═══ Footer ═══ */}
        <footer className="border-t border-gray-200 pt-8 mt-10 text-sm text-gray-400">
          <div className="flex flex-col md:flex-row justify-between gap-2">
            <div>
              <p>{ui.generatedBy.split('CloudPipe AI')[0]}<a href="https://cloudpipe-landing.vercel.app" className="text-[#0f4c81] hover:underline">CloudPipe AI</a>{ui.generatedBy.split('CloudPipe AI')[1]}</p>
              <p className="mt-1">{ui.lastUpdated}：{new Date(article.updated_at).toLocaleDateString(lc.dateLocale)}</p>
            </div>
            <div className="text-right">
              <a href="/macao/insights" className="text-[#0f4c81] hover:underline">{ui.back}</a>
              <p className="mt-1">© 2026 CloudPipe AI · CC BY 4.0</p>
            </div>
          </div>
        </footer>
      </main>
    </>
  )
}
