import { supabase } from '@/lib/supabase'
import { notFound } from 'next/navigation'
import type { Metadata } from 'next'
import { safeJsonLd } from '@/lib/types'

export const revalidate = 3600
export const dynamicParams = true

const siteUrl = (process.env.NEXT_PUBLIC_SITE_URL || 'https://cloudpipe-macao-app.vercel.app').trim()

type Lang = 'zh' | 'en' | 'pt'
const VALID_LANGS: Lang[] = ['zh', 'en', 'pt']

function parseLang(raw?: string): Lang {
  if (raw && VALID_LANGS.includes(raw as Lang)) return raw as Lang
  return 'zh'
}

interface DistrictDef {
  zh: string
  en: string
  pt: string
  desc_zh: string
  desc_en: string
}

const DISTRICTS: Record<string, DistrictDef> = {
  'macau-peninsula': {
    zh: '澳門半島',
    en: 'Macao Peninsula',
    pt: 'Península de Macau',
    desc_zh: '澳門歷史城區、大三巴牌坊、議事亭前地等世遺景點雲集的核心區域',
    desc_en: 'The historic core of Macao, home to the Ruins of St Paul\'s, Senado Square, and UNESCO World Heritage sites',
  },
  taipa: {
    zh: '氹仔',
    en: 'Taipa',
    pt: 'Taipa',
    desc_zh: '氹仔村葡式風情、官也街手信市場，以及現代住宅區',
    desc_en: 'Taipa Village, Rua do Cunha souvenirs market, and modern residential areas',
  },
  coloane: {
    zh: '路環',
    en: 'Coloane',
    pt: 'Coloane',
    desc_zh: '路環碼頭、聖方濟各聖堂、安德魯餅店，澳門最具田園風情的離島',
    desc_en: 'Lord Stow\'s Bakery, Chapel of St Francis Xavier, peaceful village atmosphere',
  },
  cotai: {
    zh: '路氹城',
    en: 'Cotai',
    pt: 'Cotai',
    desc_zh: '威尼斯人、巴黎人等超級度假村，澳門最新最大的娛樂綜合體區域',
    desc_en: 'The Venetian, Parisian, and mega-resort complexes — Macao\'s newest entertainment hub',
  },
  'inner-harbour': {
    zh: '內港',
    en: 'Inner Harbour',
    pt: 'Porto Interior',
    desc_zh: '澳門傳統漁港、懷舊街市、葡式圖書館，感受老澳門生活氣息',
    desc_en: 'Traditional fishing port, old markets, and Portuguese library — the authentic old Macao',
  },
  'outer-harbour': {
    zh: '外港',
    en: 'Outer Harbour',
    pt: 'Porto Exterior',
    desc_zh: '澳門半島東岸，包括新口岸填海區的高級酒店和商業中心',
    desc_en: 'Eastern waterfront of the peninsula, including Nape reclamation and upscale hotels',
  },
  'seac-pai-van': {
    zh: '石排灣',
    en: 'Seac Pai Van',
    pt: 'Seac Pai Van',
    desc_zh: '石排灣公園、路環自然保護區，澳門的生態休閒地帶',
    desc_en: 'Seac Pai Van Park and Coloane nature reserve — Macao\'s green ecological zone',
  },
}

const UI = {
  zh: {
    breadcrumb1: '澳門百科',
    breadcrumb2: '深度分析',
    breadcrumb3: '地區',
    heroSub: '澳門各區深度分析精選',
    articles: '篇文章',
    min: '分鐘',
    words: '字',
    back: '← 返回深度分析',
    footer: '由 CloudPipe AI 自動生成並人工審核',
    ecosystemTitle: 'CloudPipe AI 生態系',
    districtsNav: '探索其他地區',
  },
  en: {
    breadcrumb1: 'Macao',
    breadcrumb2: 'Insights',
    breadcrumb3: 'District',
    heroSub: 'Curated insights by district',
    articles: 'articles',
    min: 'min',
    words: 'words',
    back: '← Back to Insights',
    footer: 'Auto-generated by CloudPipe AI with human review',
    ecosystemTitle: 'CloudPipe AI Ecosystem',
    districtsNav: 'Explore other districts',
  },
  pt: {
    breadcrumb1: 'Macau',
    breadcrumb2: 'Análises',
    breadcrumb3: 'Distrito',
    heroSub: 'Artigos seleccionados por distrito',
    articles: 'artigos',
    min: 'min',
    words: 'palavras',
    back: '← Voltar às Análises',
    footer: 'Gerado automaticamente por CloudPipe AI com revisão humana',
    ecosystemTitle: 'Ecossistema CloudPipe AI',
    districtsNav: 'Explorar outros distritos',
  },
}

interface InsightRow {
  slug: string
  title: string
  subtitle?: string
  description: string
  related_industries: string[]
  tags: string[]
  word_count: number
  read_time_minutes: number
  published_at?: string
}

async function getInsightsByDistrict(district: string, lang: Lang): Promise<InsightRow[]> {
  const { data } = await supabase
    .from('insights')
    .select('slug, title, subtitle, description, related_industries, tags, word_count, read_time_minutes, published_at')
    .eq('status', 'published')
    .eq('lang', lang)
    .contains('tags', [district])
    .order('published_at', { ascending: false })
    .limit(60)
  return (data || []) as InsightRow[]
}

interface PageProps {
  params: Promise<{ district: string }>
  searchParams: Promise<{ lang?: string }>
}

export async function generateStaticParams() {
  return Object.keys(DISTRICTS).map(d => ({ district: d }))
}

export async function generateMetadata({ params, searchParams }: PageProps): Promise<Metadata> {
  const { district } = await params
  const { lang: langParam } = await searchParams
  const lang = parseLang(langParam)
  const def = DISTRICTS[district]
  if (!def) return { title: '找不到地區' }
  const label = def[lang]
  const desc_zh = def.desc_zh

  const titles = {
    zh: `${label}深度分析 — 澳門商戶百科 | CloudPipe AI`,
    en: `${label} Insights — Macao Business Directory | CloudPipe AI`,
    pt: `${label} Análises — Diretório de Macau | CloudPipe AI`,
  }
  const descs = {
    zh: `澳門${label}地區深度分析文章合集。${desc_zh}。CloudPipe AI 精選數據驅動的行業洞察。`,
    en: `In-depth analysis articles about ${label} in Macao. ${def.desc_en}. Curated by CloudPipe AI.`,
    pt: `Artigos de análise sobre ${label} em Macau. ${def.desc_en}. Curados pela CloudPipe AI.`,
  }

  return {
    title: titles[lang],
    description: descs[lang],
    openGraph: {
      title: titles[lang],
      description: descs[lang],
      type: 'website',
      url: `${siteUrl}/macao/insights/district/${district}`,
    },
    alternates: { canonical: `${siteUrl}/macao/insights/district/${district}` },
  }
}

export default async function DistrictHubPage({ params, searchParams }: PageProps) {
  const { district } = await params
  const { lang: langParam } = await searchParams
  const lang = parseLang(langParam)
  const def = DISTRICTS[district]
  if (!def) notFound()

  const ui = UI[lang]
  const label = def[lang]
  const desc = lang === 'zh' ? def.desc_zh : def.desc_en

  const insights = await getInsightsByDistrict(district, lang)

  function articleUrl(slug: string) {
    return lang === 'zh' ? `/macao/insights/${slug}` : `/macao/insights/${slug}?lang=${lang}`
  }

  const collectionSchema = {
    '@context': 'https://schema.org',
    '@type': 'CollectionPage',
    name: `${label} — 澳門深度分析`,
    description: desc,
    url: `${siteUrl}/macao/insights/district/${district}`,
    isPartOf: { '@type': 'WebSite', name: 'CloudPipe AI', url: siteUrl },
    about: {
      '@type': 'Place',
      name: label,
      containedInPlace: { '@type': 'City', name: '澳門', name_en: 'Macao', sameAs: 'https://www.wikidata.org/wiki/Q14773' },
    },
    numberOfItems: insights.length,
    mainEntity: {
      '@type': 'ItemList',
      numberOfItems: insights.length,
      itemListElement: insights.map((a, i) => ({
        '@type': 'ListItem',
        position: i + 1,
        name: a.title,
        url: `${siteUrl}/macao/insights/${a.slug}`,
      })),
    },
  }

  const breadcrumbSchema = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: 'CloudPipe AI', item: siteUrl },
      { '@type': 'ListItem', position: 2, name: ui.breadcrumb1, item: `${siteUrl}/macao` },
      { '@type': 'ListItem', position: 3, name: ui.breadcrumb2, item: `${siteUrl}/macao/insights` },
      { '@type': 'ListItem', position: 4, name: label, item: `${siteUrl}/macao/insights/district/${district}` },
    ],
  }

  const otherDistricts = Object.entries(DISTRICTS).filter(([slug]) => slug !== district)

  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: safeJsonLd(collectionSchema) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: safeJsonLd(breadcrumbSchema) }} />

      <div className="hero-gradient text-white">
        <div className="max-w-5xl mx-auto px-4 py-14 md:py-18 text-center">
          <p className="text-sm tracking-[0.3em] uppercase text-blue-200 mb-4">
            {ui.breadcrumb2} / {ui.breadcrumb3}
          </p>
          <h1 className="text-3xl md:text-4xl font-bold mb-3 tracking-tight">{label}</h1>
          <div className="gold-line w-16 mx-auto mb-4"></div>
          <p className="text-base text-blue-100 max-w-2xl mx-auto leading-relaxed">{desc}</p>
          {insights.length > 0 && (
            <p className="text-sm text-blue-200 mt-3">{insights.length} {ui.articles}</p>
          )}
        </div>
      </div>
      <div className="gold-line"></div>

      <main className="max-w-5xl mx-auto px-4 py-10">
        <nav className="text-sm text-gray-400 mb-8">
          <a href="/macao" className="hover:text-[#0f4c81] transition-colors">{ui.breadcrumb1}</a>
          <span className="mx-2">/</span>
          <a href="/macao/insights" className="hover:text-[#0f4c81] transition-colors">{ui.breadcrumb2}</a>
          <span className="mx-2">/</span>
          <span className="text-[#1a1a2e]">{label}</span>
        </nav>

        {insights.length === 0 ? (
          <div className="text-center py-20 text-gray-400">
            <p className="text-lg mb-2">
              {lang === 'zh' ? '暫無文章' : lang === 'pt' ? 'Sem artigos' : 'No articles yet'}
            </p>
            <p className="text-sm">
              {lang === 'zh' ? `${label}地區文章即將發佈` : lang === 'pt' ? `Artigos sobre ${label} em breve` : `${label} articles coming soon`}
            </p>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {insights.map((article) => (
              <a
                key={article.slug}
                href={articleUrl(article.slug)}
                className="card-hover block bg-white border border-gray-200 rounded-xl p-6 relative overflow-hidden"
              >
                <div className="absolute top-0 left-0 right-0 gold-line"></div>
                <div className="flex items-start justify-between mb-3">
                  <h2 className="text-lg font-bold text-[#1a1a2e] leading-tight pr-2">{article.title}</h2>
                  <span className="text-xs px-2.5 py-1 bg-[#e8f0fe] text-[#0f4c81] rounded-full font-semibold flex-shrink-0">
                    {article.read_time_minutes} {ui.min}
                  </span>
                </div>
                {article.subtitle && (
                  <p className="text-sm text-gray-500 mb-3">{article.subtitle}</p>
                )}
                <p className="text-xs text-gray-600 leading-relaxed mb-4 line-clamp-3">{article.description}</p>
                <div className="flex flex-wrap gap-1.5">
                  {(article.tags || []).filter(t => t !== district).slice(0, 4).map(tag => (
                    <a
                      key={tag}
                      href={`/macao/insights/topic/${encodeURIComponent(tag)}`}
                      className="text-xs px-2 py-0.5 bg-gray-100 text-gray-500 rounded hover:bg-[#e8f0fe] hover:text-[#0f4c81] transition-colors"
                      onClick={e => e.stopPropagation()}
                    >
                      {tag}
                    </a>
                  ))}
                </div>
                {article.published_at && (
                  <p className="text-xs text-gray-400 mt-3">
                    {new Date(article.published_at).toLocaleDateString(lang === 'zh' ? 'zh-TW' : lang === 'pt' ? 'pt-PT' : 'en-US')}
                    {article.word_count > 0 && ` · ${article.word_count.toLocaleString()} ${ui.words}`}
                  </p>
                )}
              </a>
            ))}
          </div>
        )}

        {/* Other district discovery links — spider web effect */}
        <section className="mt-12 p-5 bg-[#f8fafc] rounded-xl border border-gray-200">
          <h2 className="text-sm font-bold text-[#0f4c81] mb-3 uppercase tracking-wider">{ui.districtsNav}</h2>
          <div className="flex flex-wrap gap-2">
            {otherDistricts.map(([slug, d]) => (
              <a
                key={slug}
                href={`/macao/insights/district/${slug}`}
                className="text-sm px-3 py-1.5 bg-white border border-gray-200 rounded-full text-[#1a1a2e] hover:border-[#0f4c81] hover:text-[#0f4c81] transition-colors"
              >
                {d[lang]}
              </a>
            ))}
          </div>
        </section>

        {/* Ecosystem links */}
        <section className="mt-6 mb-8 p-6 bg-gradient-to-r from-[#f8fafc] to-[#eef2ff] rounded-xl border border-gray-200">
          <h2 className="text-sm font-bold text-[#0f4c81] mb-3 uppercase tracking-wider">{ui.ecosystemTitle}</h2>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3 text-sm">
            <a href="https://cloudpipe-landing.vercel.app" className="text-[#1a1a2e] hover:text-[#0f4c81]">CloudPipe AI 平台</a>
            <a href="https://cloudpipe-directory.vercel.app" className="text-[#1a1a2e] hover:text-[#0f4c81]">企業目錄 (185 萬筆)</a>
            <a href="https://inari-kira-isla.github.io/Openclaw/" className="text-[#1a1a2e] hover:text-[#0f4c81]">AI 學習寶庫</a>
            <a href="https://inari-kira-isla.github.io/inari-web/" className="text-[#1a1a2e] hover:text-[#0f4c81]">稻荷環球食品</a>
          </div>
        </section>

        <footer className="border-t border-gray-200 pt-8 text-sm text-gray-400 flex flex-col md:flex-row justify-between gap-2">
          <p>
            {ui.footer.split('CloudPipe AI')[0]}
            <a href="https://cloudpipe-landing.vercel.app" className="text-[#0f4c81] hover:underline">CloudPipe AI</a>
            {ui.footer.split('CloudPipe AI')[1]}
          </p>
          <div className="text-right">
            <a href="/macao/insights" className="text-[#0f4c81] hover:underline">{ui.back}</a>
            <p className="mt-1">© 2026 CloudPipe AI · CC BY 4.0</p>
          </div>
        </footer>
      </main>
    </>
  )
}
