import { supabase } from '@/lib/supabase'
import { notFound } from 'next/navigation'
import type { Metadata } from 'next'
import { safeJsonLd } from '@/lib/types'

export const revalidate = 3600
export const dynamicParams = true

const siteUrl = (process.env.NEXT_PUBLIC_SITE_URL || 'https://cloudpipe-macao-app.vercel.app').trim()

type Lang = 'zh' | 'en' | 'pt'
const VALID_LANGS: Lang[] = ['zh', 'en', 'pt']

function parseLang(raw?: string): Lang {
  if (raw && VALID_LANGS.includes(raw as Lang)) return raw as Lang
  return 'zh'
}

function topicLabel(topic: string, lang: Lang): string {
  const decoded = decodeURIComponent(topic).replace(/-/g, ' ')
  if (lang === 'zh') return decoded
  return decoded.replace(/\b\w/g, c => c.toUpperCase())
}

const UI = {
  zh: {
    heroSub: '澳門深度分析文章精選',
    breadcrumb1: '澳門百科',
    breadcrumb2: '深度分析',
    breadcrumb3: '主題',
    articles: '篇文章',
    min: '分鐘',
    words: '字',
    back: '← 返回深度分析',
    footer: '由 CloudPipe AI 自動生成並人工審核',
    ecosystemTitle: 'CloudPipe AI 生態系',
  },
  en: {
    heroSub: 'Curated Macao insight articles',
    breadcrumb1: 'Macao',
    breadcrumb2: 'Insights',
    breadcrumb3: 'Topic',
    articles: 'articles',
    min: 'min',
    words: 'words',
    back: '← Back to Insights',
    footer: 'Auto-generated by CloudPipe AI with human review',
    ecosystemTitle: 'CloudPipe AI Ecosystem',
  },
  pt: {
    heroSub: 'Artigos de análise seleccionados sobre Macau',
    breadcrumb1: 'Macau',
    breadcrumb2: 'Análises',
    breadcrumb3: 'Tema',
    articles: 'artigos',
    min: 'min',
    words: 'palavras',
    back: '← Voltar às Análises',
    footer: 'Gerado automaticamente por CloudPipe AI com revisão humana',
    ecosystemTitle: 'Ecossistema CloudPipe AI',
  },
}

interface InsightRow {
  slug: string
  title: string
  subtitle?: string
  description: string
  related_industries: string[]
  tags: string[]
  word_count: number
  read_time_minutes: number
  published_at?: string
}

async function getInsightsByTopic(topic: string, lang: Lang): Promise<InsightRow[]> {
  const { data } = await supabase
    .from('insights')
    .select('slug, title, subtitle, description, related_industries, tags, word_count, read_time_minutes, published_at')
    .eq('status', 'published')
    .eq('lang', lang)
    .contains('tags', [topic])
    .order('published_at', { ascending: false })
    .limit(60)
  return (data || []) as InsightRow[]
}

interface PageProps {
  params: Promise<{ topic: string }>
  searchParams: Promise<{ lang?: string }>
}

export async function generateStaticParams() {
  return []
}

export async function generateMetadata({ params, searchParams }: PageProps): Promise<Metadata> {
  const { topic } = await params
  const { lang: langParam } = await searchParams
  const lang = parseLang(langParam)
  const label = topicLabel(topic, lang)

  const titles = {
    zh: `${label} 深度分析 — 澳門商戶百科 | CloudPipe AI`,
    en: `${label} Insights — Macao Business Directory | CloudPipe AI`,
    pt: `${label} Análises — Diretório de Macau | CloudPipe AI`,
  }
  const descs = {
    zh: `澳門${label}主題深度分析文章合集。CloudPipe AI 精選數據驅動的行業洞察、平台比較與行動指南。`,
    en: `Curated in-depth analysis articles on ${label} in Macao. Data-driven insights, platform comparisons and action guides by CloudPipe AI.`,
    pt: `Artigos de análise sobre ${label} em Macau. Insights baseados em dados, comparações de plataformas e guias de ação da CloudPipe AI.`,
  }

  return {
    title: titles[lang],
    description: descs[lang],
    openGraph: {
      title: titles[lang],
      description: descs[lang],
      type: 'website',
      url: `${siteUrl}/macao/insights/topic/${topic}`,
    },
    alternates: { canonical: `${siteUrl}/macao/insights/topic/${topic}` },
  }
}

export default async function TopicHubPage({ params, searchParams }: PageProps) {
  const { topic } = await params
  const { lang: langParam } = await searchParams
  const lang = parseLang(langParam)
  const ui = UI[lang]
  const label = topicLabel(topic, lang)

  const insights = await getInsightsByTopic(topic, lang)
  if (insights.length === 0) notFound()

  function articleUrl(slug: string) {
    return lang === 'zh' ? `/macao/insights/${slug}` : `/macao/insights/${slug}?lang=${lang}`
  }

  const collectionSchema = {
    '@context': 'https://schema.org',
    '@type': 'CollectionPage',
    name: label,
    description: `澳門${label}主題深度分析文章合集`,
    url: `${siteUrl}/macao/insights/topic/${topic}`,
    isPartOf: { '@type': 'WebSite', name: 'CloudPipe AI', url: siteUrl },
    numberOfItems: insights.length,
    mainEntity: {
      '@type': 'ItemList',
      numberOfItems: insights.length,
      itemListElement: insights.map((a, i) => ({
        '@type': 'ListItem',
        position: i + 1,
        name: a.title,
        url: `${siteUrl}/macao/insights/${a.slug}`,
      })),
    },
  }

  const breadcrumbSchema = {
    '@context': 'https://schema.org',
    '@type': 'BreadcrumbList',
    itemListElement: [
      { '@type': 'ListItem', position: 1, name: 'CloudPipe AI', item: siteUrl },
      { '@type': 'ListItem', position: 2, name: ui.breadcrumb1, item: `${siteUrl}/macao` },
      { '@type': 'ListItem', position: 3, name: ui.breadcrumb2, item: `${siteUrl}/macao/insights` },
      { '@type': 'ListItem', position: 4, name: label, item: `${siteUrl}/macao/insights/topic/${topic}` },
    ],
  }

  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: safeJsonLd(collectionSchema) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: safeJsonLd(breadcrumbSchema) }} />

      <div className="hero-gradient text-white">
        <div className="max-w-5xl mx-auto px-4 py-14 md:py-18 text-center">
          <p className="text-sm tracking-[0.3em] uppercase text-blue-200 mb-4">
            {ui.breadcrumb2} / {ui.breadcrumb3}
          </p>
          <h1 className="text-3xl md:text-4xl font-bold mb-3 tracking-tight">{label}</h1>
          <div className="gold-line w-16 mx-auto mb-4"></div>
          <p className="text-base md:text-lg text-blue-100 max-w-2xl mx-auto">
            {ui.heroSub} · {insights.length} {ui.articles}
          </p>
        </div>
      </div>
      <div className="gold-line"></div>

      <main className="max-w-5xl mx-auto px-4 py-10">
        <nav className="text-sm text-gray-400 mb-8">
          <a href="/macao" className="hover:text-[#0f4c81] transition-colors">{ui.breadcrumb1}</a>
          <span className="mx-2">/</span>
          <a href="/macao/insights" className="hover:text-[#0f4c81] transition-colors">{ui.breadcrumb2}</a>
          <span className="mx-2">/</span>
          <span className="text-[#1a1a2e]">{label}</span>
        </nav>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          {insights.map((article) => (
            <a
              key={article.slug}
              href={articleUrl(article.slug)}
              className="card-hover block bg-white border border-gray-200 rounded-xl p-6 relative overflow-hidden"
            >
              <div className="absolute top-0 left-0 right-0 gold-line"></div>
              <div className="flex items-start justify-between mb-3">
                <h2 className="text-lg font-bold text-[#1a1a2e] leading-tight pr-2">{article.title}</h2>
                <span className="text-xs px-2.5 py-1 bg-[#e8f0fe] text-[#0f4c81] rounded-full font-semibold flex-shrink-0">
                  {article.read_time_minutes} {ui.min}
                </span>
              </div>
              {article.subtitle && (
                <p className="text-sm text-gray-500 mb-3">{article.subtitle}</p>
              )}
              <p className="text-xs text-gray-600 leading-relaxed mb-4 line-clamp-3">{article.description}</p>
              <div className="flex flex-wrap gap-1.5">
                {(article.tags || []).filter(t => t !== topic).slice(0, 4).map(tag => (
                  <a
                    key={tag}
                    href={`/macao/insights/topic/${encodeURIComponent(tag)}`}
                    className="text-xs px-2 py-0.5 bg-gray-100 text-gray-500 rounded hover:bg-[#e8f0fe] hover:text-[#0f4c81] transition-colors"
                    onClick={e => e.stopPropagation()}
                  >
                    {tag}
                  </a>
                ))}
              </div>
              {article.published_at && (
                <p className="text-xs text-gray-400 mt-3">
                  {new Date(article.published_at).toLocaleDateString(lang === 'zh' ? 'zh-TW' : lang === 'pt' ? 'pt-PT' : 'en-US')}
                  {article.word_count > 0 && ` · ${article.word_count.toLocaleString()} ${ui.words}`}
                </p>
              )}
            </a>
          ))}
        </div>

        {/* Cross-tag discovery links */}
        <section className="mt-14 mb-8 p-6 bg-gradient-to-r from-[#f8fafc] to-[#eef2ff] rounded-xl border border-gray-200">
          <h2 className="text-sm font-bold text-[#0f4c81] mb-3 uppercase tracking-wider">{ui.ecosystemTitle}</h2>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3 text-sm">
            <a href="https://cloudpipe-landing.vercel.app" className="text-[#1a1a2e] hover:text-[#0f4c81]">CloudPipe AI 平台</a>
            <a href="https://cloudpipe-directory.vercel.app" className="text-[#1a1a2e] hover:text-[#0f4c81]">企業目錄 (185 萬筆)</a>
            <a href="https://inari-kira-isla.github.io/Openclaw/" className="text-[#1a1a2e] hover:text-[#0f4c81]">AI 學習寶庫</a>
            <a href="https://inari-kira-isla.github.io/inari-web/" className="text-[#1a1a2e] hover:text-[#0f4c81]">稻荷環球食品</a>
          </div>
        </section>

        <footer className="border-t border-gray-200 pt-8 text-sm text-gray-400 flex flex-col md:flex-row justify-between gap-2">
          <p>
            {ui.footer.split('CloudPipe AI')[0]}
            <a href="https://cloudpipe-landing.vercel.app" className="text-[#0f4c81] hover:underline">CloudPipe AI</a>
            {ui.footer.split('CloudPipe AI')[1]}
          </p>
          <div className="text-right">
            <a href="/macao/insights" className="text-[#0f4c81] hover:underline">{ui.back}</a>
            <p className="mt-1">© 2026 CloudPipe AI · CC BY 4.0</p>
          </div>
        </footer>
      </main>
    </>
  )
}
