#!/usr/bin/env python3
"""
Insights → Google Sheet 多工作表同步
包含：所有文章、AI引用、類別、地區、互連、商戶、時間更新等
"""

import os
import sys
import time
from pathlib import Path
from datetime import datetime
from collections import defaultdict

def get_insights_data():
    """從 Supabase 讀取所有 insights 數據"""
    env_path = Path.home() / "Documents/cloudpipe-macao-app/.env.local"
    env_vars = {}

    with open(env_path) as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#"):
                key, val = line.split("=", 1)
                env_vars[key] = val

    from supabase import create_client

    url = env_vars.get("NEXT_PUBLIC_SUPABASE_URL")
    key = env_vars.get("SUPABASE_SERVICE_ROLE_KEY")
    sheet_id = env_vars.get("NEXT_PUBLIC_INSIGHTS_SPREADSHEET_ID")

    if not all([url, key, sheet_id]):
        print("❌ 缺少 Supabase 或 Google Sheet 配置")
        sys.exit(1)

    supabase = create_client(url, key)

    print("📊 從 Supabase 讀取 insights 數據...")

    # 直接使用查詢 API，跳過 select() 逐頁優化超時
    # 使用更小的查詢和多次較小的 batch 查詢
    all_insights = []
    page = 0
    page_size = 200  # 更小的頁面大小

    # 只查詢必要的欄位（避免 JSON 欄位序列化超時）
    columns = "slug,title,lang,tags,status,word_count,created_at,updated_at,published_at,related_merchant_slugs,related_insights,generated_by,reviewed"

    max_retries = 3
    while page < 100:  # 最多 100 頁 = 20,000 篇（足夠當前需求）
        retry_count = 0
        success = False
        while retry_count < max_retries and not success:
            try:
                result = supabase.table("insights").select(columns).order("created_at", desc=True).range(page * page_size, (page + 1) * page_size - 1).execute()
                if not result.data:
                    print(f"   📋 到達末尾，共 {len(all_insights)} 篇")
                    return all_insights, sheet_id
                all_insights.extend(result.data)
                page += 1
                print(f"   📋 已獲得 {len(all_insights)} 篇...")
                success = True
            except Exception as e:
                retry_count += 1
                if "timeout" in str(e).lower():
                    if retry_count >= max_retries:
                        print(f"   ⚠️  達到最大重試，共獲得 {len(all_insights)} 篇")
                        return all_insights, sheet_id
                    print(f"   ⏳ 超時，重試 {retry_count}/{max_retries}...")
                    time.sleep(3 * retry_count)
                else:
                    print(f"   ❌ 查詢錯誤: {str(e)[:100]}")
                    return all_insights, sheet_id

        if not success:
            break

    return all_insights, sheet_id

def prepare_sheets_data(insights):
    """準備各個工作表的數據"""
    sheets = {}

    # 1. 所有文章列表
    sheets['All Articles'] = prepare_all_articles_enhanced(insights)

    # 2. AI 引用數據（頂部）
    sheets['AI Citations'] = prepare_ai_citations(insights)

    # 3. 按類別分類
    sheets['By Category'] = prepare_by_category(insights)

    # 4. 按地區分類
    sheets['By Region'] = prepare_by_region(insights)

    # 5. Insight 互連情況
    sheets['Interconnections'] = prepare_interconnections(insights)

    # 6. 商戶連結情況
    sheets['Merchant Links'] = prepare_merchant_links(insights)

    # 7. 時間更新統計
    sheets['Update Timeline'] = prepare_update_timeline(insights)

    return sheets

def prepare_all_articles_enhanced(insights):
    """所有文章列表 + B&C 增強信息"""
    rows = [
        ["Slug", "標題", "語言", "地區", "狀態", "字數", "商戶連結數", "相關 Insights", "更新時間"]
    ]

    for insight in insights:
        slug = insight.get('slug', '-')
        title = insight.get('title', '-')
        lang = insight.get('lang', '-')
        region = slug.split('-')[0] if slug else '-'
        status = insight.get('status', '-')
        word_count = insight.get('word_count', 0)
        merchant_count = len(insight.get('related_merchant_slugs', []) or [])
        related_count = len(insight.get('related_insights', []) or [])
        updated = insight.get('updated_at', '-')[:10] if insight.get('updated_at') else '-'

        rows.append([slug, title, lang, region, status, word_count, merchant_count, related_count, updated])

    return rows

def prepare_ai_citations(insights):
    """AI 引用數據（頂部）"""
    rows = [
        ["Slug", "標題", "Generated By", "Reviewed", "Publish Date"]
    ]

    # 篩選已發布的 insights
    published = [i for i in insights if i.get('status') == 'published']
    published.sort(key=lambda x: x.get('published_at') or '', reverse=True)

    for insight in published[:500]:
        slug = insight.get('slug', '-')
        title = insight.get('title', '-')
        generated_by = insight.get('generated_by', '-')
        reviewed = "✓" if insight.get('reviewed') else "✗"
        published_date = insight.get('published_at', '-')[:10] if insight.get('published_at') else '-'

        rows.append([slug, title, generated_by, reviewed, published_date])

    return rows

def prepare_by_category(insights):
    """按類別分類"""
    rows = [
        ["Category", "Article Count", "Avg Word Count", "Top Articles"]
    ]

    categories = defaultdict(list)
    for insight in insights:
        tags = insight.get('tags', []) or []
        if tags:
            for tag in tags[:1]:  # 使用第一個標籤作為類別
                categories[tag].append(insight)
        else:
            categories['Uncategorized'].append(insight)

    for category in sorted(categories.keys()):
        articles = categories[category]
        count = len(articles)
        avg_words = sum(a.get('word_count', 0) for a in articles) // count if count > 0 else 0
        top_titles = ', '.join([a.get('title', '')[:20] for a in articles[:3]])

        rows.append([category, count, avg_words, top_titles])

    return rows

def prepare_by_region(insights):
    """按地區分類"""
    rows = [
        ["Region", "Article Count", "Languages", "Total Words", "Avg Update Gap (days)"]
    ]

    regions = defaultdict(list)
    for insight in insights:
        slug = insight.get('slug', '-')
        region = slug.split('-')[0] if slug else 'unknown'
        regions[region].append(insight)

    for region in sorted(regions.keys()):
        articles = regions[region]
        count = len(articles)
        langs = set(a.get('lang', '-') for a in articles)
        total_words = sum(a.get('word_count', 0) for a in articles)

        # 計算平均更新間隔
        dates = [a.get('updated_at', '') for a in articles if a.get('updated_at')]
        avg_gap = '-'
        if len(dates) > 1:
            dates.sort(reverse=True)
            gaps = []
            for i in range(len(dates)-1):
                d1 = datetime.fromisoformat(dates[i].replace('Z', '+00:00'))
                d2 = datetime.fromisoformat(dates[i+1].replace('Z', '+00:00'))
                gaps.append((d1 - d2).days)
            avg_gap = sum(gaps) // len(gaps) if gaps else 0

        rows.append([region, count, len(langs), total_words, avg_gap])

    return rows

def prepare_interconnections(insights):
    """Insight 互連情況"""
    rows = [
        ["Slug", "Related Insights Count"]
    ]

    for insight in insights[:500]:
        slug = insight.get('slug', '-')
        related = insight.get('related_insights', []) or []
        rows.append([slug, len(related)])

    return rows

def prepare_merchant_links(insights):
    """商戶連結情況"""
    rows = [
        ["Slug", "Merchant Links Count", "Top Merchants", "Last Update"]
    ]

    for insight in insights[:300]:
        slug = insight.get('slug', '-')
        merchants = insight.get('related_merchant_slugs', []) or []
        merchant_count = len(merchants)
        top_merchants = ', '.join(merchants[:5])
        updated = insight.get('updated_at', '-')[:10] if insight.get('updated_at') else '-'

        rows.append([slug, merchant_count, top_merchants, updated])

    return rows

def prepare_update_timeline(insights):
    """時間更新統計"""
    rows = [
        ["Date", "Articles Updated", "Total Words Added", "Articles Created"]
    ]

    update_stats = defaultdict(lambda: {'count': 0, 'words': 0, 'created': 0})

    for insight in insights:
        updated = insight.get('updated_at', '')
        created = insight.get('created_at', '')

        if updated:
            date = updated[:10]
            update_stats[date]['count'] += 1
            update_stats[date]['words'] += insight.get('word_count', 0)

        if created:
            date = created[:10]
            update_stats[date]['created'] += 1

    for date in sorted([d for d in update_stats.keys() if d], reverse=True)[:90]:
        stats = update_stats[date]
        rows.append([date, stats['count'], stats['words'], stats['created']])

    return rows

def push_to_google_sheets(sheets_data, sheet_id):
    """推送多個工作表到 Google Sheet"""
    print(f"\n📤 推送數據到 Google Sheet...")

    try:
        from google.oauth2.credentials import Credentials
        from googleapiclient.discovery import build
    except ImportError:
        print("❌ Google API 庫未安裝")
        return False

    creds_file = Path.home() / ".credentials/token.json"

    if not creds_file.exists():
        print("❌ Google 認證未設置")
        return False

    creds = Credentials.from_authorized_user_file(str(creds_file))
    sheets_api = build('sheets', 'v4', credentials=creds)

    # 批量更新所有工作表
    requests = []
    for sheet_name, rows in sheets_data.items():
        print(f"   📝 {sheet_name}: {len(rows)} 行")

        # 新增工作表
        requests.append({
            'addSheet': {
                'properties': {
                    'title': sheet_name,
                    'gridProperties': {
                        'rowCount': len(rows) + 100,
                        'columnCount': len(rows[0]) if rows else 10
                    }
                }
            }
        })

    # 執行批量新增工作表
    if requests:
        try:
            body = {'requests': requests}
            sheets_api.spreadsheets().batchUpdate(spreadsheetId=sheet_id, body=body).execute()
            print(f"   ✅ 新增 {len(requests)} 個工作表")
        except Exception as e:
            print(f"   ⚠️  工作表可能已存在: {str(e)[:80]}")

    # 寫入每個工作表的數據
    for sheet_name, rows in sheets_data.items():
        try:
            sheets_api.spreadsheets().values().update(
                spreadsheetId=sheet_id,
                range=f"'{sheet_name}'!A1",
                valueInputOption='RAW',
                body={'values': rows}
            ).execute()
            print(f"   ✅ {sheet_name} 寫入完成")
        except Exception as e:
            print(f"   ❌ {sheet_name} 失敗: {str(e)[:80]}")

    print(f"\n✅ 同步完成！")
    print(f"   📊 Google Sheet: https://docs.google.com/spreadsheets/d/{sheet_id}/edit")

    return True

def main():
    print("╔═══════════════════════════════════════════════╗")
    print("║  📊 Insights → Google Sheet 多工作表同步   ║")
    print("╚═══════════════════════════════════════════════╝\n")

    try:
        insights, sheet_id = get_insights_data()
        sheets_data = prepare_sheets_data(insights)
        push_to_google_sheets(sheets_data, sheet_id)

    except Exception as e:
        print(f"\n❌ 同步失敗: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)

if __name__ == "__main__":
    main()
