-- 20260725_fix_crawler_stats_cache_stale_via_mv.sql
--
-- ROOT CAUSE (confirmed 2026-07-25 via direct psql + pg_cron introspection):
--   1. pg_cron job 'refresh-crawler-stats-cache' (jobid=1) was switched at some
--      point after 2026-05-31 to call refresh_crawler_stats_cache_v2() only
--      (command: "SET LOCAL statement_timeout = '60s'; SELECT refresh_crawler_stats_cache_v2();").
--      refresh_crawler_stats_cache_v2() only REFRESHes the 4 mv_crawler_*_30d
--      materialized views — it never writes to crawler_stats_cache.
--   2. The OLD refresh_crawler_stats_cache() (the function that actually writes
--      the crawler_stats_cache table every downstream consumer reads) is no
--      longer called by ANY scheduled job. It only ran when something hit the
--      RPC directly (e.g. aeo_monitor_hourly.py trigger_refresh()).
--   3. That old function does a full ad-hoc scan of crawler_visits (30d window,
--      several GROUP BYs materialized via a CTE) which takes ~7-8s when run
--      directly. When invoked through PostgREST-facing roles (authenticated/
--      anon/authenticator all have statement_timeout=8s / 3s configured on the
--      role, see pg_roles.rolconfig), it gets killed by Postgres error 57014
--      (query_canceled) before finishing — confirmed via direct curl RPC call
--      (8.27s wall time, 57014) and independently by introspecting pg_roles.
--   4. Net effect: crawler_stats_cache.daily_30d / daily_by_owner_30d froze
--      around 2026-06-04 and never advanced, silently, because the whole
--      function body is wrapped in `EXCEPTION WHEN OTHERS THEN RAISE WARNING`
--      (see historical add_crawler_stats_cache_auto_refresh.sql lines ~108-111)
--      which swallows the 57014 and skips the UPSERT entirely.
--
-- FIX (this migration):
--   A. Rewrite refresh_crawler_stats_cache() to read from the 4 already-fresh
--      mv_crawler_*_30d materialized views (refreshed every 30 min by the
--      existing v2 cron job, confirmed fresh: computed_at = today, MAX(day)
--      on mv_crawler_daily_30d = today) instead of re-scanning crawler_visits
--      via a slow CTE. Only two lightweight independent queries remain against
--      crawler_visits directly (total_visits_90d, sites_breakdown) because
--      neither is covered by any MV — both benchmarked at ~2s each using the
--      existing idx_crawler_visits_ts / idx_crawler_visits_site_ts indexes,
--      not the slow multi-aggregate CTE that caused the timeout.
--   B. Chain refresh_crawler_stats_cache() onto the SAME pg_cron job right
--      after refresh_crawler_stats_cache_v2(), so crawler_stats_cache gets
--      refreshed automatically every 30 min again, using MV data that was
--      just refreshed in the preceding statement of the same job run.
--   C. Add crawler_stats_cache.last_refresh_error so a stuck/failing refresh
--      is visible from the table itself (not just pg_cron / dashboard logs).
--
-- CONSUMERS THAT NEED ZERO CHANGES because they only read the
-- crawler_stats_cache TABLE (not the MVs directly):
--   - aeo_monitor_hourly.py       (reads total_visits_1d/7d)
--   - cohort_20day_tracker.py     (reads via crawler_stats_cache SSOT)
--   - analysis_to_bulletin_bridge.py (reads total_visits_1d/7d, daily_30d)
--   - daily_data_cross_validator.py  (reads daily_by_owner_30d local mirror)
--   - crawler_stats_precompute.py (reads bots_breakdown/sites_breakdown/
--     industries_breakdown/daily_30d/daily_by_owner_30d — all field names
--     and JSON shapes are preserved unchanged below)
--   - /api/v1/crawler-stats/route.ts (reads the precomputed GitHub Pages
--     cache generated by crawler_stats_precompute.py above; not this table
--     directly, but that script's output is only as fresh as this table)
--   - crawler_rca_engine.py:675 calls RPC refresh_crawler_stats_cache
--     (non-v2) — function name/signature unchanged, still valid.
--
-- BEHAVIOR NOTE (intentional, documented tradeoff):
--   industries_breakdown now comes from mv_crawler_industries_30d, which
--   excludes the 'insights' pseudo-industry and spider-web/page/robots/
--   api-faq/faqs page_types (per 20260530_exclude_insights_from_industries.sql
--   — a deliberate 2026-05-29 fix to stop 'insights' masking real industry
--   distribution). The OLD deployed refresh_crawler_stats_cache() body (see
--   ROLLBACK below) did NOT have the insights exclusion for this particular
--   table (only get_crawler_summary() had been fixed). This migration brings
--   crawler_stats_cache.industries_breakdown in line with that documented,
--   intentional fix rather than preserving the stale/undocumented divergence.
--
-- sites_breakdown DISPOSITION: grep across the whole repo + the 5 python
-- consumer scripts (aeo_monitor_hourly / cohort_20day_tracker /
-- analysis_to_bulletin_bridge / daily_data_cross_validator /
-- crawler_rca_engine) shows sites_breakdown IS actively read by
-- crawler_stats_precompute.py (both the local-db path and the
-- _precompute_from_supabase fallback path: `sites = cache_row.get(
-- 'sites_breakdown', {})`, then used to compute site_ratios for the
-- dashboard's per-site split). Because it IS consumed, this migration adds
-- a lightweight standalone GROUP BY site query (not a re-run of the slow
-- multi-aggregate CTE) — benchmarked ~2s.
--
-- ROLLBACK: restore the function body below (captured via
-- pg_get_functiondef('public.refresh_crawler_stats_cache()'::regprocedure)
-- immediately before this migration was applied, 2026-07-25 13:xx UTC):
--
-- CREATE OR REPLACE FUNCTION public.refresh_crawler_stats_cache()
--  RETURNS void
--  LANGUAGE plpgsql
--  SECURITY DEFINER
-- AS $function$
-- DECLARE
--   v_since_30d TIMESTAMPTZ;
--   v_since_7d  TIMESTAMPTZ;
--   v_since_90d TIMESTAMPTZ;
--   v_today_hkt TIMESTAMPTZ;
-- BEGIN
--   PERFORM set_config('statement_timeout', '180000', true);
--   v_since_30d := NOW() - INTERVAL '30 days';
--   v_since_7d  := NOW() - INTERVAL '7 days';
--   v_since_90d := NOW() - INTERVAL '90 days';
--   v_today_hkt := (DATE_TRUNC('day', NOW() AT TIME ZONE 'Asia/Hong_Kong'))
--                    AT TIME ZONE 'Asia/Hong_Kong';
--   INSERT INTO crawler_stats_cache (
--     id, total_visits_1d, total_visits_7d, total_visits_30d, total_visits_90d,
--     unique_bots, bots_breakdown, sites_breakdown, industries_breakdown,
--     daily_30d, daily_by_owner_30d, generated_at
--   )
--   WITH v30 AS MATERIALIZED (
--     SELECT ts, bot_name, bot_owner, site, industry, page_type
--     FROM crawler_visits WHERE ts >= v_since_30d
--   ),
--   counts AS (
--     SELECT COUNT(*) AS total_30d,
--            COUNT(*) FILTER (WHERE ts >= v_today_hkt) AS total_1d,
--            COUNT(*) FILTER (WHERE ts >= v_since_7d) AS total_7d,
--            COUNT(DISTINCT bot_name) AS uniq_bots
--     FROM v30
--   ),
--   cnt_90d AS (SELECT COUNT(*) AS total_90d FROM crawler_visits WHERE ts >= v_since_90d),
--   bots_agg AS (
--     SELECT jsonb_object_agg(bot_name, jsonb_build_object('count', cnt, 'owner', bot_owner)) AS j
--     FROM (SELECT bot_name, bot_owner, COUNT(*) cnt FROM v30 GROUP BY bot_name, bot_owner ORDER BY cnt DESC LIMIT 50) b
--   ),
--   sites_agg AS (
--     SELECT jsonb_object_agg(site_key, cnt) AS j
--     FROM (SELECT COALESCE(LOWER(site), 'cloudpipe-macao-app') site_key, COUNT(*) cnt FROM v30 GROUP BY 1 ORDER BY cnt DESC) s
--   ),
--   industries_agg AS (
--     SELECT jsonb_object_agg(industry_key, cnt) AS j
--     FROM (SELECT COALESCE(NULLIF(industry, ''), 'unknown') industry_key, COUNT(*) cnt FROM v30
--           WHERE page_type IS NULL OR page_type NOT IN ('spider-web', 'page', 'robots', 'api-faq', 'faqs')
--           GROUP BY 1 ORDER BY cnt DESC LIMIT 50) i
--   ),
--   daily_agg AS (
--     SELECT jsonb_object_agg(day, cnt ORDER BY day) AS j
--     FROM (SELECT ((ts AT TIME ZONE 'Asia/Hong_Kong')::date)::text AS day, COUNT(*) cnt FROM v30 GROUP BY 1) d
--   )
--   SELECT 1, c.total_1d, c.total_7d, c.total_30d, c90.total_90d, c.uniq_bots,
--          ba.j, sa.j, ia.j, da.j, NULL, NOW()
--   FROM counts c, cnt_90d c90, bots_agg ba, sites_agg sa, industries_agg ia, daily_agg da
--   ON CONFLICT (id) DO UPDATE SET
--     total_visits_1d = EXCLUDED.total_visits_1d, total_visits_7d = EXCLUDED.total_visits_7d,
--     total_visits_30d = EXCLUDED.total_visits_30d, total_visits_90d = EXCLUDED.total_visits_90d,
--     unique_bots = EXCLUDED.unique_bots, bots_breakdown = EXCLUDED.bots_breakdown,
--     sites_breakdown = EXCLUDED.sites_breakdown, industries_breakdown = EXCLUDED.industries_breakdown,
--     daily_30d = EXCLUDED.daily_30d,
--     daily_by_owner_30d = COALESCE(EXCLUDED.daily_by_owner_30d, crawler_stats_cache.daily_by_owner_30d),
--     generated_at = EXCLUDED.generated_at;
-- EXCEPTION WHEN OTHERS THEN
--   RAISE WARNING 'refresh_crawler_stats_cache failed: %', SQLERRM;
-- END;
-- $function$;
--
-- and revert the cron job with:
--   SELECT cron.alter_job(1, command => $$SET LOCAL statement_timeout = '60s'; SELECT refresh_crawler_stats_cache_v2();$$);

BEGIN;

-- ---------------------------------------------------------------------------
-- C. Visibility: last_refresh_error so a stuck refresh is visible from the
--    table itself, not just pg_cron/dashboard logs.
-- ---------------------------------------------------------------------------
ALTER TABLE public.crawler_stats_cache
  ADD COLUMN IF NOT EXISTS last_refresh_error TEXT;

-- ---------------------------------------------------------------------------
-- A. New function body: read from the 4 fresh MVs instead of re-scanning
--    crawler_visits. Field names / JSON shapes unchanged for all consumers.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.refresh_crawler_stats_cache()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $function$
DECLARE
  v_since_90d      TIMESTAMPTZ := NOW() - INTERVAL '90 days';
  v_since_30d      TIMESTAMPTZ := NOW() - INTERVAL '30 days';
  v_total_1d       INTEGER;
  v_total_7d       INTEGER;
  v_total_30d      INTEGER;
  v_total_90d      INTEGER;
  v_unique_bots    INTEGER;
  v_bots           JSONB;
  v_sites          JSONB;
  v_industries     JSONB;
  v_daily          JSONB;
  v_daily_by_owner JSONB;
BEGIN
  -- Give this a generous ceiling too (kept from the previous version) —
  -- should be moot now since every branch below is fast, but protects
  -- against a future regression silently reintroducing a slow scan.
  PERFORM set_config('statement_timeout', '30000', true);

  -- ── 1) total_visits_1d/7d/30d + unique_bots: single-row MV, already fresh ──
  SELECT total_visits_1d, total_visits_7d, total_visits_30d, unique_bots
    INTO v_total_1d, v_total_7d, v_total_30d, v_unique_bots
  FROM public.mv_crawler_total_visits_30d;

  -- ── 2) total_visits_90d: not covered by any MV — lightweight independent
  --      count using idx_crawler_visits_ts (~2s benchmarked, not the slow
  --      multi-aggregate CTE that caused the original timeout) ──
  SELECT COUNT(*) INTO v_total_90d
  FROM public.crawler_visits WHERE ts >= v_since_90d;

  -- ── 3) bots_breakdown: { bot_name: { count, owner } } — from mv_crawler_bots_30d,
  --      same "predominant owner per bot_name" reduction as get_crawler_summary() ──
  SELECT jsonb_object_agg(bot_name, jsonb_build_object('count', total_cnt, 'owner', top_owner))
    INTO v_bots
  FROM (
    SELECT
      bot_name,
      SUM(visit_count) AS total_cnt,
      (array_agg(bot_owner ORDER BY visit_count DESC NULLS LAST))[1] AS top_owner
    FROM public.mv_crawler_bots_30d
    GROUP BY bot_name
    ORDER BY total_cnt DESC
    LIMIT 50
  ) b;

  -- ── 4) sites_breakdown: { site: count } — no MV covers this (mv_crawler_
  --      industries_30d only has industries). Consumed by
  --      crawler_stats_precompute.py (site_ratios) — confirmed via grep, so
  --      it cannot be left null. Lightweight independent GROUP BY using
  --      idx_crawler_visits_site_ts (~2s benchmarked), not the slow CTE. ──
  SELECT jsonb_object_agg(site_key, cnt) INTO v_sites
  FROM (
    SELECT COALESCE(LOWER(site), 'cloudpipe-macao-app') AS site_key, COUNT(*) AS cnt
    FROM public.crawler_visits
    WHERE ts >= v_since_30d
    GROUP BY 1
    ORDER BY cnt DESC
  ) s;

  -- ── 5) industries_breakdown: { industry: count } — from mv_crawler_industries_30d
  --      (already excludes 'insights' pseudo-industry + spider-web/page/robots/
  --      api-faq/faqs page_types per 20260530_exclude_insights_from_industries.sql) ──
  SELECT jsonb_object_agg(industry, visit_count) INTO v_industries
  FROM (
    SELECT industry, visit_count
    FROM public.mv_crawler_industries_30d
    ORDER BY visit_count DESC
    LIMIT 50
  ) i;

  -- ── 6) daily_30d: { "YYYY-MM-DD": count } — from mv_crawler_daily_30d,
  --      summed across bot_owner (HKT day bucketing already baked into the MV) ──
  SELECT jsonb_object_agg(day::text, day_total ORDER BY day) INTO v_daily
  FROM (
    SELECT day, SUM(visit_count) AS day_total
    FROM public.mv_crawler_daily_30d
    GROUP BY day
  ) d;

  -- ── 7) daily_by_owner_30d: { "YYYY-MM-DD": { owner: count } } — mv_crawler_daily_30d
  --      already has (day, bot_owner, visit_count), so this is a direct nested agg ──
  SELECT jsonb_object_agg(day::text, owners ORDER BY day) INTO v_daily_by_owner
  FROM (
    SELECT day, jsonb_object_agg(bot_owner, visit_count) AS owners
    FROM public.mv_crawler_daily_30d
    GROUP BY day
  ) o;

  INSERT INTO public.crawler_stats_cache (
    id, total_visits_1d, total_visits_7d, total_visits_30d, total_visits_90d,
    unique_bots, bots_breakdown, sites_breakdown, industries_breakdown,
    daily_30d, daily_by_owner_30d, generated_at, last_refresh_error
  ) VALUES (
    1, v_total_1d, v_total_7d, v_total_30d, v_total_90d,
    v_unique_bots, v_bots, v_sites, v_industries,
    v_daily, v_daily_by_owner, NOW(), NULL
  )
  ON CONFLICT (id) DO UPDATE SET
    total_visits_1d      = EXCLUDED.total_visits_1d,
    total_visits_7d      = EXCLUDED.total_visits_7d,
    total_visits_30d     = EXCLUDED.total_visits_30d,
    total_visits_90d     = EXCLUDED.total_visits_90d,
    unique_bots          = EXCLUDED.unique_bots,
    bots_breakdown        = EXCLUDED.bots_breakdown,
    sites_breakdown       = EXCLUDED.sites_breakdown,
    industries_breakdown  = EXCLUDED.industries_breakdown,
    daily_30d             = EXCLUDED.daily_30d,
    daily_by_owner_30d    = EXCLUDED.daily_by_owner_30d,
    generated_at          = EXCLUDED.generated_at,
    last_refresh_error    = NULL;

EXCEPTION WHEN OTHERS THEN
  -- Fail-loud, visible from the table itself (not just pg_cron/warning logs).
  -- Kept as a genuine safety net now that the happy path is fast — this
  -- should rarely fire, so if it does, it is worth someone's attention.
  RAISE WARNING 'refresh_crawler_stats_cache failed: %', SQLERRM;
  UPDATE public.crawler_stats_cache
    SET last_refresh_error = SQLERRM || ' @ ' || NOW()::text
    WHERE id = 1;
END;
$function$;

-- ---------------------------------------------------------------------------
-- B. Chain refresh_crawler_stats_cache() onto the existing v2 cron job so
--    crawler_stats_cache table auto-refreshes every 30 min again, using MV
--    data that was just refreshed by the preceding statement in the same
--    job run (same-transaction read-your-own-writes; jobid=1 already proven
--    to run multi-statement commands successfully — see cron.job_run_details
--    history, 10-30s per run, well inside the existing 60s SET LOCAL budget).
-- ---------------------------------------------------------------------------
SELECT cron.alter_job(
  1,
  command => $cron$SET LOCAL statement_timeout = '60s'; SELECT refresh_crawler_stats_cache_v2(); SELECT refresh_crawler_stats_cache();$cron$
);

COMMIT;

-- Run once immediately to seed/verify (outside the transaction so a failure
-- here doesn't roll back the function/cron changes above — matches the
-- original migration's own pattern of "run once immediately to seed").
SELECT refresh_crawler_stats_cache();
